jupyterlab/lumino

CONTRIBUTING.md
README.md
RELEASE.md

Updating readme

---

packages/poll/api-extractor.json
packages/poll/package.json
packages/poll/src/index.ts
packages/poll/src/poll.ts
packages/poll/src/ratelimiter.ts
packages/poll/tdoptions.json
packages/poll/tests/karma.conf.js
packages/poll/tests/src/index.spec.ts
packages/poll/tests/tsconfig.json
packages/poll/tests/webpack.config.js
packages/poll/tsconfig.json

Fixes https://github.com/jupyterlab/lumino/issues/17
cf. https://github.com/jupyterlab/jupyterlab/issues/7598

Add @lumino/poll package.

---

examples/example-datastore/package.json
packages/datagrid/package.json

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

chore(build): Add missing package.json dependencies

---

packages/datagrid/package.json
packages/datastore/package.json

Found when I clicked on the link in npmjs.org. Searched the repository and found only these two files.
Thanks!
Bruno

Fix typo in project URL

---

packages/datagrid/src/celleditor.ts
packages/default-theme/style/datagrid.css

Fixes issue highlighted at end of https://github.com/jupyterlab/lumino/issues/61#issuecomment-601843447

Fix namespacing for 'invalid' classname

---

packages/widgets/src/dockpanel.ts

Fixes issue pointed out at the end of this PR: 
https://github.com/jupyterlab/lumino/pull/66#discussion_r420248675

Fix boolean logic when false is specified

---

packages/datagrid/src/datagrid.ts

fixes the type of region in `columnCount` method

fix columnCount signature

---

packages/default-theme/style/tabbar.css
packages/widgets/src/tabbar.ts
packages/widgets/style/tabbar.css

Option on TabBars to allow inline editing of tab titles.

Double-click to edit tab title in TabBars

---

packages/virtualdom/src/index.ts
packages/widgets/src/menu.ts
packages/widgets/src/menubar.ts

Based on the phosphor PR https://github.com/phosphorjs/phosphor/pull/405

Add aria roles to menus

---

packages/datagrid/src/textrenderer.ts

Text wrapping is enabled with a boolean flag (default is false). It will first attempt to split the text into words based on whitespace and wrap that way. If the text can not be split into words, it will apply "classic" wrapping based on characters.

Add text wrapping

---

packages/datagrid/src/datagrid.ts

Fix https://github.com/jupyterlab/lumino/issues/144

Make _repaintRegion a protected method

---

packages/datagrid/src/datagrid.ts

Remove leftover SectionResizeRequest

---

README.md

https://lumino.readthedocs.io/en/stable/

Update RTD Link to Point to Stable Version

---

packages/datagrid/src/basicmousehandler.ts

Reverting the `_pressData` --> `pressData` change and getter removal in #161

Restore getter for _pressData

---

examples/example-datagrid/src/index.ts
packages/datagrid/src/basicmousehandler.ts
packages/datagrid/src/celleditor.ts
packages/datagrid/src/celleditorcontroller.ts
packages/datagrid/src/cellgroup.ts
packages/datagrid/src/datagrid.ts
packages/datagrid/src/datamodel.ts
packages/datagrid/src/index.ts

This PR introduces initial cell merging support for the lumino DataGrid. Immense thanks to @mbektasbbg for his mentorship and support during this project - it would not be possible without him.
To maintain consistency with the existing data model API, groupCount() and group() methods have been added to the data model ABC. Here is an example of an implementing class:
```typescript
groupCount(region: DataModel.RowRegion): number {
if (region === 'body') {
return 3;
} else if (region === 'column-header') {
return 1;
} else if (region === 'row-header') {
return 2;
} else if (region === 'corner-header') {
return 1;
}
return 0;
}
group(region: DataModel.CellRegion, groupIndex: number): CellGroup | null {
if (region === 'body') {
return [{startRow: 1, startColumn: 1, endRow: 2, endColumn: 2}, …
```

Cell merging

---

package.json
yarn.lock

Update lerna dependency to pick up security update (affects dev environment only).

Update Lerna Dependency

---

CHANGELOG.md

Automated Changelog Entry for 2021.6.10 on master
Python version: 2021.6.10
npm version: lumino-top-level: 2021.4.27
@lumino/example-datagrid: 0.22.1
@lumino/example-dockpanel: 0.12.0
@lumino/example-datastore: 0.12.0
@lumino/widgets: 1.23.0
@lumino/datagrid: 0.25.1
@lumino/application: 1.20.0
@lumino/default-theme: 0.14.0 …

Automated Changelog Entry for 2021.6.10 on master

---

CHANGELOG.md

Automated Changelog Entry for 2021.7.19 on master
Python version: 2021.7.19
npm version: lumino-top-level: 2021.6.10
@lumino/example-datastore: 0.12.0
@lumino/example-datagrid: 0.22.1
@lumino/example-dockpanel: 0.12.0
@lumino/widgets: 1.23.0
@lumino/datagrid: 0.25.1
@lumino/default-theme: 0.14.0
@lumino/application: 1.20.0 …

Automated Changelog Entry for 2021.7.19 on master

---

packages/widgets/src/contextmenu.ts
packages/widgets/tests/src/contextmenu.spec.ts
packages/widgets/tests/src/index.spec.ts

Don't sort context menu item by selector

---

packages/widgets/src/menubar.ts

Added option to force items' position

---

CHANGELOG.md

Automated Changelog Entry for 2017.7.22 on master
Python version: 2017.7.22
npm version: lumino-top-level: 2021.7.21
@lumino/example-datastore: 0.14.0
@lumino/example-datagrid: 0.24.0
@lumino/example-dockpanel: 0.14.0
@lumino/widgets: 1.25.0
@lumino/datagrid: 0.27.0
@lumino/default-theme: 0.16.0
@lumino/application: 1.22.0 …

Automated Changelog Entry for 2017.7.22 on master

---

CHANGELOG.md

We did not complete the release on 2021.7.22

Remove Errant Changelog Entry

---

CHANGELOG.md

Automated Changelog Entry for 2021.8.3 on master
Python version: 2021.8.3
npm version: lumino-top-level: 2021.7.23
@lumino/example-datagrid: 0.25.0
@lumino/example-accordionpanel: 0.2.0
@lumino/example-datastore: 0.15.0
@lumino/example-dockpanel: 0.15.0
@lumino/default-theme: 0.17.0
@lumino/application: 1.23.0
@lumino/datagrid: 0.28.0
@lumino/widgets: 1.26.0 …

Automated Changelog Entry for 2021.8.3 on master

---

.github/workflows/tests.yml
package.json

Move link checking to a separate job and use new check-links action from jupyter_releaser.

Use Check Links Action

---

CHANGELOG.md

Automated Changelog Entry for 2021.8.23 on master
Python version: 2021.8.23
npm version: lumino-top-level: 2021.8.12
@lumino/example-datagrid: 0.26.0
@lumino/example-accordionpanel: 0.2.2
@lumino/example-datastore: 0.15.2
@lumino/example-dockpanel: 0.15.2
@lumino/polling: 1.6.2
@lumino/keyboard: 1.5.2
@lumino/messaging: 1.7.2
@lumino/signaling: 1.7.2
@lumino/algorithm: 1.6.2
@lumino/dragdrop: 1.10.2
@lumino/collections: 1.6.2
@lumino/default-theme: 0.17.2
@lumino/commands: 1.15.2
@lumino/virtualdom: 1.11.2
@lumino/coreutils: 1.8.2
@lumino/domutils: 1.5.2
@lumino/application: 1.23.2
@lumino/datagrid: 0.30.0
@lumino/widgets: 1.26.2
@lumino/disposable: 1.7.2
@lumino/datastore: 0.14.2 …

Automated Changelog Entry for 2021.8.23 on master

---

.github/jupyterlab-probot.yml
binder/README.md
binder/environment.yaml
binder/postBuild
binder/start

Add binder config and `jupyterlab-probot` config to add binder links to PRs.

Add binder configuration

---

packages/widgets/src/accordionpanel.ts

Bug seen in https://github.com/jupyterlab/jupyterlab/pull/10653

Class and aria attribute must be changed on title

---

packages/virtualdom/src/index.ts
review/api/virtualdom.api.md

Fixes https://github.com/jupyterlab/lumino/issues/236
h/t @SnarkBoojum

Remove deprecated MediaStreamErrorEvent

---

.github/workflows/tests.yml
.gitignore
CONTRIBUTING.md
README.md
packages/datagrid/src/datagrid.ts

Add linter check in CI

---

README.md
binder/README.md
docs/source/conf.py

Update references to main branch (`master` → `main`), follow up to #269

Update references to main branch (`master` → `main`)

---

packages/coreutils/package.json
packages/coreutils/rollup.config.js
packages/coreutils/src/index.common.ts
packages/coreutils/src/index.node.ts
packages/coreutils/src/index.ts
packages/coreutils/src/random.browser.ts
packages/coreutils/src/random.node.ts
packages/coreutils/src/uuid.browser.ts
packages/coreutils/src/uuid.node.ts
packages/coreutils/src/uuid.ts

chore(coreutils):  Refactor Node v Browser builds

---

package.json
packages/dragdrop/src/index.ts
packages/widgets/src/dockpanel.ts

fix(DockPanel):  Drag and Drop fails when hosted in a ShadowRoot

---

packages/widgets/src/docklayout.ts

Follow-up https://github.com/jupyterlab/lumino/pull/281#discussion_r784146881

Improve DockLayout code documentation

---

CHANGELOG.md

Automated Changelog Entry Forward Ported from v2022.8.8

Automated Changelog Entry Forward Ported from v2022.8.8

---

examples/example-accordionpanel/package.json
examples/example-datagrid/package.json
examples/example-dockpanel-amd/package.json
examples/example-dockpanel-iife/package.json
examples/example-dockpanel/package.json
packages/algorithm/package.json
packages/application/package.json
packages/collections/package.json
packages/commands/package.json
packages/coreutils/package.json
packages/datagrid/package.json
packages/default-theme/package.json
packages/disposable/package.json
packages/domutils/package.json
packages/dragdrop/package.json
packages/keyboard/package.json
packages/messaging/package.json
packages/polling/package.json
packages/properties/package.json
packages/signaling/package.json
packages/virtualdom/package.json
packages/widgets/package.json

Bump all packages to next major version - alpha
except the examples (minor version bump).

First Lumino 2 pre-release

---

.licenserc.yaml

The file was commit directly hence the error did not show up

Fix license header following 231f01c

---

README.md

This video series was mentioned in the semi-weekly Juptyer Accessibility call, so I thought it should be added to the README.

Add section to README: Learning Resources

---

packages/application/src/index.ts
packages/application/tests/src/index.spec.ts
review/api/application.api.md

This add an optional description to application plugin to allow documentation to be reported programmatically.

Add plugin description

---

CHANGELOG.md
packages/polling/src/poll.ts

Revert "Backport PR #395 on branch 1.x (Switch to using `setTimeout` for all deferred processing.)"

---

packages/datagrid/src/datagrid.ts
packages/widgets/src/commandpalette.ts
packages/widgets/tests/src/widget.spec.ts

Those changes are from code scan analysis: https://github.com/jupyterlab/lumino/security/code-scanning

Fix minor code scan warnings

---

packages/virtualdom/src/index.ts
packages/widgets/src/contextmenu.ts
packages/widgets/src/menu.ts
packages/widgets/src/menubar.ts
packages/widgets/tests/src/menu.spec.ts
review/api/widgets.api.md

Backport PR https://github.com/jupyterlab/lumino/pull/432

Backport PR #432 on branch 1.x (Avoid menu layout trashing by moving DOM queries)

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts
packages/widgets/src/commandpalette.ts
packages/widgets/src/menu.ts

Backport PR #433 on branch 1.x (Add support for list of keystrokes)

---

packages/signaling/package.json
packages/signaling/src/index.ts
packages/signaling/tests/src/index.spec.ts
review/api/signaling.api.md

Backport PR #443 on branch 1.x (Add blocking signal feature)

---

examples/example-menubar/index.html
examples/example-menubar/package.json
examples/example-menubar/rollup.config.js
examples/example-menubar/src/index.ts
examples/example-menubar/style/content.css
examples/example-menubar/style/index.css
examples/example-menubar/tsconfig.json
examples/example-menubar/webpack.config.js
packages/widgets/src/menubar.ts
packages/widgets/tests/src/menubar.spec.ts

Backport #465 on branch 1.x (Improve the menubar accessibility)

---

packages/application/src/index.ts
packages/application/tests/src/index.spec.ts
packages/application/tests/tsconfig.json

Backport PR #377 on branch 1.x (Dynamic extensions reloading)

---

CHANGELOG.md

Automated Changelog Entry for 2022.12.13 on 1.x
```
@lumino/example-accordionpanel: 0.8.6
@lumino/example-datagrid: 0.32.6
@lumino/example-datastore: 0.21.6
@lumino/example-dockpanel: 0.21.6
@lumino/example-menubar: 0.1.1
@lumino/example-nested-dockpanel-amd: 0.4.1
@lumino/application: 1.31.1
@lumino/commands: 1.21.0
@lumino/datagrid: 0.36.6
@lumino/datastore: 0.18.3
@lumino/default-theme: 0.22.6
@lumino/disposable: 1.10.3
@lumino/dragdrop: 1.14.3
@lumino/polling: 1.11.3
@lumino/signaling: 1.11.0
@lumino/virtualdom: …
```

Automated Changelog Entry for 2022.12.13 on 1.x

---

CHANGELOG.md

Automated Changelog Entry for 2023.1.19 on 1.x
```
@lumino/example-accordionpanel: 0.8.7
@lumino/example-datagrid: 0.32.7
@lumino/example-datastore: 0.21.7
@lumino/example-dockpanel: 0.21.7
@lumino/example-menubar: 0.1.2
@lumino/example-nested-dockpanel-amd: 0.4.1
@lumino/application: 1.31.2
@lumino/commands: 1.21.0
@lumino/datagrid: 0.36.7
@lumino/datastore: 0.18.3
@lumino/default-theme: 0.22.7
@lumino/disposable: 1.10.3
@lumino/dragdrop: 1.14.3
@lumino/polling: 1.11.3
@lumino/signaling: 1.11.0
@lumino/virtualdom: …
```

Automated Changelog Entry for 2023.1.19 on 1.x

---

packages/signaling/package.json
packages/signaling/src/index.ts
packages/signaling/tests/src/index.spec.ts
review/api/signaling.api.md

https://github.com/jupyterlab/lumino/pull/444#issuecomment-1400395192
This reverts commit c90adeee035170719731ccb58c06dfdc1c925460.

Revert "Add blocking signal feature (#443)"

---

packages/widgets/style/widget.css

Fixes #533 
Remove CSS cursor rule on Widget.

Remove cursor style

---

buildutils/package.json

Fix following https://github.com/jupyterlab/lumino/actions/runs/4255282463

Set publication to public

---

CHANGELOG.md

Remove changelogs from 2.x pre-release

Backport changelog from 1.x

---

.github/workflows/prep-release.yml
.github/workflows/publish-release.yml
.github/workflows/tests.yml
package.json

Update releaser workflow to support automatic NPM tag and set provenance

Upgrade releaser workflows

---

RELEASE.md

Fix names of the workflows in `RELEASE.md`

Update releaser workflow names

---

examples/example-accordionpanel/package.json
examples/example-datagrid/package.json
examples/example-dockpanel/package.json
examples/example-menubar/package.json
packages/application/package.json
packages/commands/package.json
packages/datagrid/package.json
packages/default-theme/package.json
packages/widgets/package.json
yarn.lock

There are only two PRs with code changes:
- https://github.com/jupyterlab/lumino/pull/662
- https://github.com/jupyterlab/lumino/pull/689

Update versions for new release

---

packages/algorithm/web-test-runner.config.js
packages/application/web-test-runner.config.js
packages/collections/web-test-runner.config.js
packages/commands/web-test-runner.config.js
packages/coreutils/web-test-runner.config.js
packages/datagrid/web-test-runner.config.js
packages/default-theme/web-test-runner.config.js
packages/disposable/web-test-runner.config.js
packages/domutils/web-test-runner.config.js
packages/dragdrop/web-test-runner.config.js
packages/keyboard/web-test-runner.config.js
packages/messaging/web-test-runner.config.js
packages/polling/web-test-runner.config.js
packages/properties/web-test-runner.config.js
packages/signaling/web-test-runner.config.js
packages/virtualdom/web-test-runner.config.js
packages/widgets/tests/src/docklayout.spec.ts
packages/widgets/tests/src/menu.spec.ts
packages/widgets/web-test-runner.config.js

This is a follow-up of the error pushed as part of #732

Forbid .only and .skip on CI

---

README.md

| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/d6352416-bec6-434a-a366-7d782bb26b0d) | ![image](https://github.com/user-attachments/assets/1fb6b813-42a5-415b-ae62-0a577c42b12a) |

Fix test status badge
