jupyterlab/lumino

packages/coreutils/src/json.ts
packages/coreutils/tests/src/json.spec.ts

This adds partial JSON typings, in what should be a minor-release compatible manner.
~Note: A (possibly) backwards incompatible way to do this in the next major release might be to use recursive types: http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#more-recursive-type-aliases~ (edited as this is only loosely related by touching the same code)

Add partial json types

---

notebooks/.babelrc
notebooks/IdGeneration.ipynb
notebooks/README.md
notebooks/package.json

This PR adds a notebooks directory with configuration to write notebooks in TypeScript that can import from the local lumino packages. There is a sample notebook that does some tests of different serialization schemes for indices. The goal would be to start adding notebook-based narrative documentation for lumino (at least the parts that don't need to render things to the page.

Add notebooks directory with example Typescript notebook.

---

packages/commands/src/index.ts

`normalizeKeys` is a very useful function for handling key shortcuts in a
platform aware way.
This function is planned to be used in jupyterlab for resolving conflicts in keyboard shortcuts.
Reference: https://github.com/jupyterlab/jupyterlab/pull/7335

Move normalizeKeys to CommandRegistry and export it.

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts

Fixes https://github.com/jupyterlab/lumino/issues/10

Add data attribute to suppress keyboard shortcuts in a region of an application.

---

packages/algorithm/package.json
packages/application/package.json
packages/collections/package.json
packages/commands/package.json
packages/coreutils/package.json
packages/datagrid/package.json
packages/datastore/package.json
packages/default-theme/package.json
packages/disposable/package.json
packages/domutils/package.json
packages/dragdrop/package.json
packages/keyboard/package.json
packages/messaging/package.json
packages/properties/package.json
packages/signaling/package.json
packages/virtualdom/package.json
packages/widgets/package.json

At the suggestion of @afshin,
1. Changed the github links to point to jupyterlab/lumino
2. Changed lumino -> Lumino in the description field.

Fix lumino links

---

packages/widgets/src/dockpanel.ts

Allow user to enable / disable tab dragging at runtime.
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

Enable / disable runtime tab dragging in DockPanel

---

packages/polling/src/poll.ts

The standby value generated in the line above is ignored in the current code if it is a boolean. This makes it actually be used where intended.

Use the standby value generated instead of ignoring it.

---

packages/virtualdom/package.json
packages/virtualdom/src/index.ts
packages/virtualdom/tests/src/index.spec.ts
packages/virtualdom/tests/tsconfig.json
packages/virtualdom/tests/webpack.config.js
packages/virtualdom/tsconfig.json
packages/widgets/package.json
packages/widgets/src/tabbar.ts
packages/widgets/src/title.ts
packages/widgets/tests/src/menubar.spec.ts
packages/widgets/tests/src/tabbar.spec.ts

Fixes phosphorjs/phosphor#395, phosphorjs/phosphor#436, and probably a bunch of other issues.
This PR adds the hpass function and VirtualElementPass class described in phosphorjs/phosphor#436.
This PR was originally phosphorjs/phoshor#437. @blink1073 Since you reviewed the original PR, could you please take a look at this one too?

Adds a "pass thru" virtual element

---

packages/algorithm/tests/webpack.config.js
packages/application/tests/webpack.config.js
packages/collections/tests/webpack.config.js
packages/commands/tests/webpack.config.js
packages/coreutils/tests/webpack.config.js
packages/datastore/tests/webpack.config.js
packages/disposable/tests/webpack.config.js
packages/domutils/tests/webpack.config.js
packages/dragdrop/tests/webpack.config.js
packages/keyboard/tests/webpack.config.js
packages/messaging/tests/webpack.config.js
packages/polling/tests/webpack.config.js
packages/properties/tests/webpack.config.js
packages/signaling/tests/webpack.config.js
packages/virtualdom/tests/webpack.config.js
packages/widgets/tests/webpack.config.js

Ref: https://github.com/jupyterlab/lumino/issues/21#issuecomment-567859371
Recently in #31, we upgraded the Webpack used to build the tests in all of the `@lumnio` packages from `v2` => `v4`.  
Webpack `v4` [adds a default value to `output.path`](https://webpack.js.org/configuration/output/#outputpath): `path.join(process.cwd(), 'dist')`. So currently, while our tests sucessfully build, they end up in the `tests/dist/build` dir, and Karma can't find them. This makes all of our test cases empty but successful. This PR fixes that

Fix `output.path` for webpack 4

---

packages/algorithm/tests/webpack.config.js
packages/application/tests/webpack.config.js
packages/collections/tests/webpack.config.js
packages/commands/tests/webpack.config.js
packages/coreutils/tests/webpack.config.js
packages/datastore/tests/webpack.config.js
packages/disposable/tests/webpack.config.js
packages/domutils/tests/webpack.config.js
packages/dragdrop/tests/webpack.config.js
packages/keyboard/tests/webpack.config.js
packages/messaging/tests/webpack.config.js
packages/polling/tests/webpack.config.js
packages/properties/tests/webpack.config.js
packages/signaling/tests/webpack.config.js
packages/virtualdom/src/index.ts
packages/virtualdom/tests/webpack.config.js
packages/widgets/src/tabbar.ts
packages/widgets/tests/webpack.config.js

cf #29, https://github.com/jupyterlab/lumino/pull/29#discussion_r359318649
This improves the handling of the set of attributes of an hpass virtualdom element. With this PR, the handling of attrs for h and hpass elements now use mostly the same code path.
This is branched off of #35, so that PR should go in before this one

Improve handling of attributes for hpass virtualdom elements

---

packages/virtualdom/tests/tsconfig.json
packages/virtualdom/tsconfig.json

@lumino/virtualdom@1.4.0 triggers a warning on webpack because it references a source map that's not disted.
This PR stops tsc from generating sourcemaps in @lumino/virtualdom, so it's consistent with the other packages

Remove 'sourceMap' from tsconfig in `@lumino/virtualdom`

---

.gitignore
packages/virtualdom/src/index.ts
packages/virtualdom/tests/src/index.spec.ts
packages/widgets/src/tabbar.ts
packages/widgets/src/title.ts

This PR contains a massive simplification and a number of improvements to the implementation of virtual nodes with custom renderers (formerly known as "passthru" virtual nodes) in the virtualdom pkg.
Ideally this PR will get pulled in sometime in the next week. so that I can incorporate its improvements into jlab before the 2.0 release, since it may involve some breaking changes in jlab (see note bellow about breaking changes w.r.t. lumino).
Overview of changes:
- I removed `VirtualElementPass` and `hpass` and folded their implementations into `VirtualElement` and `h`. A custom renderer (what I had formerly been calling a "passthru" renderer) can now be set on any virtual node via an optional arg to either `VirtualElement` or `h`. This has a number of benefits:
- reduced the number of …

Simplified/improved custom rendering of virtual nodes: removed `hpass` and `VirtualElementPass`, added optional `renderer` param

---

.gitignore
packages/commands/package.json
packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts
packages/commands/tsconfig.json
packages/virtualdom/package.json
packages/virtualdom/src/index.ts
packages/widgets/package.json
packages/widgets/src/commandpalette.ts
packages/widgets/src/menu.ts
packages/widgets/src/menubar.ts
packages/widgets/src/tabbar.ts
packages/widgets/src/title.ts
packages/widgets/tests/src/tabbar.spec.ts
packages/widgets/tests/src/title.spec.ts

needed for jupyterlab/jupyterlab#7864
This PR has two goals:
- I recently got this bit of feedback from one of the `LabIcon` early adopters (@vidartf [via gitter](https://gitter.im/jupyterlab/jupyterlab?at=5e3d3ec7433e1d40399f5d07)):
> by inspecting the lab source, I figured `iconRenderer` was the attribute to set
He was talking about figuring out that `Title.iconRenderer` was the field you're supposed to pass a `LabIcon` object into. Which, fair point, it's pretty confusing that `LabIcon` gets passed into the `Foo.icon` field for all interfaces except those defined in Lumino. On top of that, `iconRenderer` as a name is kind of clunky and maybe a bit conceptually confusing. Given all that, I want to experiment with reclaiming the deprecated `Title.icon` field, and see if I can do so in a …

IRenderer cleanup; normalize icon fields across all interfaces

---

packages/polling/package.json
packages/signaling/tests/src/index.spec.ts

This PR removes references to broken links. The original signaling issues are lost and the polling URL was incorrect.

Fix broken links in polling package and signaling tests.

---

README.md

Hi,
Adding an external examples section to readme, with the link to an example with Lumino + Vue.js.
Ref: https://github.com/jupyterlab/lumino/issues/3#issuecomment-596542091
Cheers
Bruno

Add an external examples section, with the vue example

---

examples/example-datagrid/src/index.ts
packages/datagrid/src/datagrid.ts
packages/datagrid/src/sectionlist.ts

The datagrid currently has a hard-coded minimum size of 10 pixels for row heights and column widths. This PR exposes a setting similar to defaultSizes to allow the user to set the minimum size for each dimension.

Customize minimum row and column section sizes for datagrid

---

packages/widgets/src/dockpanel.ts

The current implementation binds the value of tabsMovable in the DockPanel constructor, so the behavior is inconsistent in the following case:
1. Create a new DockPanel with `tabsMovable=false`.
2. Later change `DockPanel.tabsMovable` to `true`.
3. Newly created TabBars will still set `tabsMovable` to false.

Fixes tabsMovable on DockPanel

---

packages/coreutils/package.json

In Webpack 5, builtin nodejs modules are no longer automatically polyfilled. This means that any project packaging lumino coreutils with webpack 5 will need to include either a polyfill or tell webpack to not package the module.
Looking at the current state of polyfills, the webpack-recommended package, crypto-browserify, does not implement the needed randomBytes (https://github.com/crypto-browserify/crypto-browserify/blob/460a13b5bf1e4ea60dc995906ba0543f7933a32b/example/bundle.js#L408). Additionally, “modern” browsers (FF 34, Chrome 37, Safari 6.1, IE 11) will use their own native crypto functions, so we do not need a module. Also, in a browser, polyfills for the crypto modules should implement the window.crypto interface rather than providing a module replacing the npm module.
In short, …

Tell bundlers to not package a crypto module for the browser.

---

packages/signaling/src/index.ts

Let `A` be an object which sends and receives signals, `B` an object which sends a signal received by `A`.
References to the object `A` are present as:
1. `signal.sender` property of the connections associated to `A` in the `receiversForSender` `WeakMap`.
1. `thisArg` property of the connections associated to `A` in the `sendersForReceiver` `WeakMap`.
1. `thisArg` property of a connection associated to `B` in the `receiversForSender` `WeakMap`.
Calling `Signal.ClearAll` on `A`, when `A` is disposed, removes the references mentioned in the points 1 and 2, but does'not remove the reference mentioned in 3. This leads to memory leaks ([see here][1]).
This PR should fix this issue.
Regards
[1]: https://github.com/jupyterlab/jupyterlab/issues/8371

Fix `disconnectAll` implementation.

---

packages/default-theme/style/commandpalette.css
packages/widgets/src/commandpalette.ts
packages/widgets/style/commandpalette.css

Fixes - #56 
Jupyter Lab Issue - [6617](https://github.com/jupyterlab/jupyterlab/issues/6617)
Added type search to input to show clear search icon. It will solve usability issue by user should be able to use mouse click to clear search text.

Added type search to command pallet search input

---

packages/datagrid/src/celleditor.ts

make sure cell editor unsubscribes from grid's wheel messages when editor is disposed
fixes #62

unsubscribe from grid wheel events on editor dispose

---

packages/datagrid/src/celleditor.ts

Hi, my name is Kalen, and I am one of the Jupyter Cal Poly interns. Our team has been using the `TextCellEditor` class in attempts to create an editable DataGrid for the extension my team is working on, [Tabular Data Editor](https://github.com/jupytercalpoly/jupyterlab-tabular-data-editor). However, the cell editor renders behind the `DataGrid`, and I think this is because the [`updatePosition`](https://github.com/jupyterlab/lumino/blob/master/packages/datagrid/src/celleditor.ts#L604-L623) method in `CellEditor` uses the styles `top` and `left`, but the `position` isn't set. In the Tabular Data Editor, I created a class called `CSVTextCellEditor` with this as the only fix and the cell editor now renders in front of the `DataGrid`.
You can see the changes I made to the Tabular Data Editor …

CellEditors now render in front of the DataGrid

---

packages/datagrid/src/basicmousehandler.ts

Hi, my name is Logan McNichols. I am an intern for Jupyter Cal Poly, working with @kgoo124 and @ryuntalan to develop a tabular data editor powered by the `DataGrid`. We want to add a grab cursor for moving rows and columns. The class `BasicMouseHandler` in the package `@lumino/datagrid` provides much of the core functionality we need, but it is difficult modify the default cursor behavior.
This pull request would move the method `cursorForHandle` from the `Private` namespace to a public method within the `BasicMouseHandler` class. Implementations of `cursorForHandle` in `BasicMouseHandler` would be updated to reflect this change. The type `ResizeHandle` would be exported as well so that classes extending `BasicMouseHandler` could create custom versions of `cursorForHandle`.
Fixes #91

Make cursorForHandle and it's argument type accessible from outside BasicMouseHandler.

---

packages/datagrid/src/datagrid.ts

Hi, my name is Logan McNichols. I am an intern for Jupyter Cal Poly, working with @kgoo124 and @ryuntalan to develop a tabular data editor powered by the DataGrid.
We noticed that submitting a `'rows-moved'` or `'columns-moved'` signal to the `DataGrid` does not seem to update it visually. I believe this is because, unlike the methods which handle adding or removing rows or columns, the methods `_onRowsMoved` and `_onColumnsMoved` do not call `_syncViewport() `.
This pull request would replace `_onRowsMoved` and `_onColumnsMoved` call to `_repaintOverlay` with a call to `_syncViewport`. It would also update the comments above these lines of code to reflect the change.
Fixes #93

Have the DataGrid syncViewport when receiving a DataModel.ChangedArgs signal of type "rows-moved" or "columns-moved"

---

packages/dragdrop/src/index.ts

Hi, my name is Logan McNichols. I am an intern for Jupyter Cal Poly. I am working on a tabular data editor powered by the datagrid along with @kgoo124 and @ryuntalan.
We would like to use lumino's `Drag` class to create a column/row shadow which appears on a mouse click of a column/row header and is drag-able. The movement of this shadow can't just follow the cursor wherever it goes, but must be constrained to the bounds of the `DataGrid`. This PR would allow us to do this, by letting us extend `Drag` and make modifications to `moveDragImage`.
This PR would rename `_moveDragImage` to `moveDragImage` and update it's implementations to reflect this change. It would remove the **private** access modifier and relocate `moveDragImage` to the area where the other public methods are.
fixes #95

Change the Drag class's private method _moveDragImage to a public method moveDragImage.

---

packages/datastore/src/listfield.ts
packages/datastore/tests/src/listfield.spec.ts

Hi, my name is Logan McNichols. I am an intern for Jupyter Cal Poly. I am working on a tabular data editor powered by the DataGrid along with @kgoo124 and @ryuntalan.
We are relying on the Datastore to store some data for us. In particular, we have two `ListField<number>` objects tracking the position of rows and columns respectively. I encountered some unexpected behavior when trying to work with a `ListField<number>` object who's length was greater than 100000.
I think I traced the problem to the function in `listfield.ts` called `spliceArray`. It was producing odd behavior when its argument `items` had length greater than 100000. With a slight modification to line 682, I think it is now having the intended mutation on `arr`.
Fixes #100

Modified function spliceArray in datastore/src/listfield.ts so that it behaves like Array.splice on large inputs.

---

packages/widgets/src/dockpanel.ts
packages/widgets/tests/src/dockpanel.spec.ts

each() will abort on first false, so setting tabsMovable=false on a DockPanel with multiple tabs will only set the first one false.

Fix for DockPanel.tabsMovable to set false to all tabs

---

packages/datagrid/src/datagrid.ts

Hi, my name is Logan McNichols. I am an intern for Jupyter Cal Poly. I am working on a tabular data editor powered by the `DataGrid` along with @kgoo124 and @ryuntalan.
We are working on a design that involves painting `LabIcons` onto the `DataGrid`'s canvas to correspond the the type of field in a given column. To achieve this, we would like to provide getters for some of the `DataGrid`'s properties and change some `private` methods to `protected`.
This PR would change the access modifier from `private` to `protected` on the following methods.
- `paintContent`
`repaintContent` 
& `repaintOverlay`
It would also add getters for the following properties.
- `_canvasGC`
- `_rowSections`
- `_columnSections`
- `_columnHeaderSections`
- `_rowHeaderSections`.
Fixes #110

Give extending classes access to some of the data grid's paint utilities.

---

packages/datagrid/src/basicmousehandler.ts

I am currently working on the Tabular Data Editor extension with @lmcnichols and @ryuntalan. We noticed the BasicMouseHandler doesn't utilize the different selection modes onMouseDown. This change would set the proper `selectionMode` during the `onMouseDown()` function. There are other places in the mouse handler where the grid is selecting certain areas, so those could also be changed as well.

mouseDown now uses cell, column, and row selection modes

---

examples/example-datagrid/src/index.ts
packages/datagrid/src/textrenderer.ts

This PR (https://github.com/phosphorjs/phosphor/pull/341) was sitting latent on the phosphor repo - I ported it over to lumino. I removed the optionality of eliding text - I feel like in almost all cases it looks better visually, although if you feel otherwise i can add the option back. I also improved the margins around the text a bit for easier readability.

Text eliding with ellipsis on datagrid text renderer

---

packages/datagrid/src/datagrid.ts

Hi, my name is Logan McNichols. I am an intern for Jupyter Cal Poly. I am working on a tabular data editor powered by the DataGrid along with @kgoo124 and @ryuntalan.
This pull request would make the `DataGrid`'s private method `_drawCornerHeaderRegion` a protected `drawCornerHeaderRegion`. It is helpful for extending classes to be able to access this method to repaint the `'corner-header'` as the last paint operation.
Fixes #115

Make private _drawCornerHeaderRegion protected drawCornerHeaderRegion

---

packages/commands/src/index.ts

Extensions are using the `commandExecuted` signal to observe user actions at a broad level (for telemetry for example). The previous comment was vague about when it is ok to use this signal. The new comment clarifies the underlying issue.

Improve note about performance of commandExecuted handlers.

---

packages/widgets/style/tabbar.css

This fixes a typo from commit 45c6f21.
If you need to reproduce the issue, you can roll back an application with a dock panel to widgets@1.9.7 and default-theme@0.1.8, and compare the responsiveness of the tab bar to an application built at the latest versions.

Fix sluggish tab dragging in the tab bar.

---

packages/commands/src/index.ts

This allows interfaces (including accessible ones) to indicate to the user that the command may toggle state.

Add isToggleable command state

---

packages/widgets/src/commandpalette.ts
packages/widgets/tests/src/commandpalette.spec.ts

Currently, the `CommandPallette` has no item to batch add an Array of commands. Instead, users must add an item one at a time via the `addItem` method. This has a performance impact if the user wants to add a large list of items since `refresh` is called after adding each item. In a 3rd party plugin we are trying to leverage, the performance impact of refreshing after adding every item was making it unusable which has motivated this proposed enhancement to the API.
This pull request adds a new method: `addItems` which allows the user to supplies an Array of items to be added rather than needing to iterate and call `addItem` for each.  Upon all the items being added, `refresh` is called then only once.

Batch Add Items to Command Pallette

---

packages/default-theme/package.json
packages/default-theme/style/index.js
packages/dragdrop/package.json
packages/dragdrop/style/index.js
packages/widgets/package.json
packages/widgets/style/index.js

The webpack css-loader plugin does not deduplicate css that is imported via the css @import. Making the css available via a js module import lets webpack do deduplication at the module level in a way that respects the dependency ordering.
Adding these index.js files should not affect anything in Lumino itself, but just make it easier to consume the Lumino CSS and have deduplication.
This will help fix a problem in JupyterLab, for example, where the Lumino widget CSS will be duplicated on the page dozens of times because many modules require the CSS files directly (so css-loader is used). With this change, modules will be able to require the style/index.js module, so Webpack itself will deduplicate the imports, and the Lumino CSS will only be put on the page once.
The default-theme package …

Add style index.js files to optionally consume the CSS via a js module import

---

packages/default-theme/package.json
packages/dragdrop/package.json
packages/widgets/package.json

This styleModule key is the convention we are adopting in JupyterLab for specifying such imports.
See https://github.com/jupyterlab/jupyterlab/pull/9427

Specify the CSS javascript module imports explicitly in package.json.

---

packages/widgets/src/dockpanel.ts
packages/widgets/tests/src/dockpanel.spec.ts

This pull request is a modification to [this one](https://github.com/jupyterlab/lumino/pull/52), by [jtpio](https://github.com/jtpio). I would have committed there, but obviously don't have write access.
It makes the constraining of tabs to their source dock panel an opt-in feature, through the `tabsConstrained` option and property, and fixes #43.

Constrain tabs to their source DockPanel (opt-in)

---

packages/datagrid/src/basicmousehandler.ts

This is useful for subclasses to know what is currently happening

DataGrid mouse handler: Expose pressData for subclasses

---

packages/widgets/src/widget.ts

This fix is related to jupyterlab/jupyterlab#9491
This PR adds `tag` to the `IOptions` object that can be passed into the `widget` constructor:
- if `node` is unset and:
- `tag` is unset: the widget's node will be a new `div` element (same as before) 
- `tag` is set: the widget's node will be a new element of tag `tag`
- if `node` is set, `tag` will always be ignored, since no new element construction will occur

Allow passing of `tag` into `widget` constructor

---

packages/widgets/src/commandpalette.ts

Follow-up to #129 to add the aria role of checkbox and the checked state to toggleable commands in the command palette.

Add checkbox aria role to toggleable commands

---

packages/widgets/src/docklayout.ts
packages/widgets/src/dockpanel.ts
packages/widgets/src/tabbar.ts
packages/widgets/src/tabpanel.ts

From the original PR:
> This builds on phosphorjs/phosphor#405 to also add ARIA roles to tabs. Merge phosphorjs/phosphor#405 first.
This PR takes all of the work done for phosphorjs/phosphor#406, a PR onto the old phosphor repo, and rebases it onto the latest lumino master.
This PR covers all of the following commits: https://github.com/jasongrout/phosphor/compare/aria-menus...jasongrout:aria-tabs. In theory, all of the other commits listed in phosphorjs/phosphor#406 should be covered by #131, which merged all of the work from phosphorjs/phosphor#405 into lumino.
@jasongrout Can you please take a look and make sure this reflects your original work? Also, what would be a good way to double check that this work is still working as intended in the context of lumino?

Add ARIA roles to tabs - lumino update

---

packages/datagrid/src/basicmousehandler.ts

Whilst the BasicMouseHandler class can be extended, it has two private properties, making extensions tricky to implement. This PR makes the the _pressData property protected instead of private.

Change one BasicMouseHandler properties from private to protected 

---

packages/datagrid/src/basicselectionmodel.ts

This PR adds the ability to toggle single row or column selections when clicking on a row or column whilst holding the Ctrl key.

Ctrl-click to toggle single row or column selections

---

packages/polling/tdoptions.json

- fixes #154
- `yarn docs`
- see that `docs/api/polling/index.html` exists and looks right
- see that `docs/api/disposable/index.html` exists and looks right
If not a bridge too far, I would happily these to this PR:
- add a `yarn docs:check` to verify the integrity of the docs build
- add to docs step on `.github/workflows`
- the docs _do_ get built, but adding the `check` would avoid future issues
- upload them as an artifact so they can be reviewed

Fix docs target for polling

---

examples/example-datagrid/package.json
examples/example-datastore/package.json
examples/example-dockpanel/package.json
packages/algorithm/package.json
packages/application/package.json
packages/collections/package.json
packages/commands/package.json
packages/coreutils/package.json
packages/datagrid/package.json
packages/datastore/package.json
packages/disposable/package.json
packages/domutils/package.json
packages/dragdrop/package.json
packages/keyboard/package.json
packages/messaging/package.json
packages/polling/package.json
packages/properties/package.json
packages/signaling/package.json
packages/virtualdom/package.json
packages/widgets/package.json
tsconfigdoc.json
yarn.lock

Fixes jupyterlab/lumino#170
We will have to save TypeScript 4.0 for a major version bump.
For reference, it looks like TS was last updated in https://github.com/jupyterlab/lumino/pull/157

Switch to TypeScript 3.9

---

packages/widgets/src/menubar.ts

This change is for accessibility - it allows ambulatory users to access the menu bar without using a mouse. Not sure what the motivation behind setting tabindex to -1 was - @sccolbert it looks like you added that in, what was the purpose of that? 
Changes the tabindex for the menu bar DOM element to be 0 instead of -1.
Allows users to bring focus to the menu bar without using a mouse.

Fix tabindex for menu bar

---

docs/source/api_index.html
docs/source/conf.py
examples/example-datagrid/package.json
examples/example-datastore/package.json
examples/example-dockpanel/package.json
package.json
packages/algorithm/package.json
packages/application/package.json
packages/collections/package.json
packages/commands/package.json
packages/coreutils/package.json
packages/datagrid/package.json
packages/datastore/package.json
packages/disposable/package.json
packages/domutils/package.json
packages/dragdrop/package.json
packages/keyboard/package.json
packages/messaging/package.json
packages/polling/package.json
packages/properties/package.json
packages/signaling/package.json
packages/virtualdom/package.json
packages/widgets/package.json
yarn.lock

Follow-up to #172 
Fixes https://github.com/jupyterlab/lumino/issues/170
Adds a hard-coded `api/index.html` file for now until we can upgrade TypeScript.

Switch back to TypeScript 3.6

---

packages/widgets/src/tabbar.ts

Currently tabs on the tab bar always show the close icon, even if the tab isn't closable.

Respect closable attribute on title

---

packages/datagrid/src/basicmousehandler.ts

This PR reverts the changes from commit https://github.com/jupyterlab/lumino/commit/4a685fc4697910daf49ccc7fc6036668b16a8ed5 as they break the `selectionMode` parameter of `BasicSelectionModel`, resulting in 'cell' selection regardless of the parameter passed to the constructor:
```js
new BasicSelectionModel({
dataModel: model6,
selectionMode: "row", // won't work
});
```
That change was arguably not needed to begin with as 'cell' selection mode will select full rows or columns when they are clicked on.

Fix selection mode

---

examples/example-dockpanel/src/index.ts
packages/default-theme/style/tabbar.css
packages/widgets/src/dockpanel.ts
packages/widgets/src/tabbar.ts
packages/widgets/src/tabpanel.ts
packages/widgets/style/tabbar.css
packages/widgets/tests/src/tabbar.spec.ts

This PR implements a plus button on the TabBar (similar to google chrome) that will trigger an event when clicked. I've wired up this event for the TabPanel to emit a AddWidgetRequested event, which can be handled by the end user to create the appropriate widget and add it to the panel. A similar approach can also be implemented for the DockPanel if desired.
The CSS is a bit tricky - currently the plus button floats to the end of the TabBar instead of following the tabs.

Implement plus button on TabBar

---

packages/datagrid/src/datagrid.ts

This PR fixes an issue where Chrome automatically scrolls to the center of an element when the `.focus()` method is triggered on a Node element. This behaviour results in context menus being rendered out of position when they are opened on an element which is not focused.
For reference: https://www.chromestatus.com/feature/5745122025144320

Remove Chrome default scroll on focus

---

packages/datagrid/src/cellgroup.ts
packages/datagrid/src/datagrid.ts

This PR:
- fixes a bug where `config.width` was wrong for the inorder leftmost child of a merged cell hierarchy.
- restores optimization for grids with no merged cell regions
- simplifies rendering logic for grids with merged cell regions
~EDIT: Will confirm when ready.~

Simplify rendering logic for grids with merged cells

---

CHANGELOG.md

Automated Changelog Entry for 2021.7.21 on master
Python version: 2021.7.21
npm version: lumino-top-level: 2021.7.19
@lumino/example-datastore: 0.13.0
@lumino/example-datagrid: 0.23.0
@lumino/example-dockpanel: 0.13.0
@lumino/widgets: 1.24.0
@lumino/datagrid: 0.26.0
@lumino/default-theme: 0.15.0
@lumino/application: 1.21.0 …

Automated Changelog Entry for 2021.7.21 on master

---

packages/widgets/src/contextmenu.ts
packages/widgets/tests/src/contextmenu.spec.ts

Follow-up of #203
To actually solve the issue #202, this adds an option to not group items by target when going up in the DOM hierarchy.

Add option to not group context menu item by target

---

.github/workflows/tests.yml
package.json

Fixes issues in check release job.
Adds Python and Pip Cache actions and fix link cache config.
Moves tagging of versions to before-draft-release to avoid confusing the second changelog check before release.

Fixes for Check Release

---

CHANGELOG.md

Automated Changelog Entry for 2021.7.23 on master
Python version: 2021.7.23
npm version: lumino-top-level: 2021.7.21
@lumino/example-datastore: 0.14.0
@lumino/example-datagrid: 0.24.0
@lumino/example-dockpanel: 0.14.0
@lumino/widgets: 1.25.0
@lumino/datagrid: 0.27.0
@lumino/default-theme: 0.16.0
@lumino/application: 1.22.0 …

Automated Changelog Entry for 2021.7.23 on master

---

examples/example-accordionpanel/index.html
examples/example-accordionpanel/package.json
examples/example-accordionpanel/src/index.ts
examples/example-accordionpanel/style/content.css
examples/example-accordionpanel/style/index.css
examples/example-accordionpanel/tsconfig.json
examples/example-accordionpanel/webpack.config.js
examples/example-dockpanel/webpack.config.js
packages/default-theme/style/accordionpanel.css
packages/default-theme/style/index.css
packages/default-theme/style/index.js
packages/widgets/src/accordionlayout.ts
packages/widgets/src/accordionpanel.ts
packages/widgets/src/boxlayout.ts
packages/widgets/src/docklayout.ts
packages/widgets/src/index.ts
packages/widgets/src/splitlayout.ts
packages/widgets/src/splitpanel.ts
packages/widgets/src/utils.ts
packages/widgets/style/accordionpanel.css
packages/widgets/style/index.css
packages/widgets/tests/src/accordionlayout.spec.ts
packages/widgets/tests/src/accordionpanel.spec.ts
packages/widgets/tests/src/index.spec.ts

This PR adds an accordion panel (including an example).
Features:
- Build on top of `SplitPanel` - multiple region of the accordion panel can be opened simulatenously and resized at will
- Keyboard navigation:
- Tab to loop on sections and content of opened sections
- Space and Enter opens/closes the section
- Up / Down (for vertical) or Left / Right (for horizontal) Arrow to loop on section titles
- Home / End to jump to first or last titles
Tasks:

Add accordion panel

---

.github/workflows/tests.yml

Since there is no python package for lumino, use a cache key that is today's date.

Fix handling of pip cache in CI

---

examples/example-datagrid/src/index.ts
packages/datagrid/src/basicmousehandler.ts
packages/datagrid/src/hyperlinkrenderer.ts
packages/datagrid/src/index.ts

This PR adds support for `HyperlinkRenderer` : a custom renderer based on `TextRenderer`, which adds logic for displaying and opening hyperlinks.
As it extends `TextRenderer`, parameters such as `font`, `color` and `background` can all be customised as expected. `HyperlinkRenderer` adds two additional parameters on top - `url` and `urlName`. Both take functions which control the logic of how to arrive at the actual `href` value for the URL, as well as any friendly name for displaying the hyperlink in the grid. In addition, the default text color and font weight for links rendered in `HyperlinkRenderer` are navy blue and **bold**.
Columns rendered with `HyperlinkRenderer` will have a pointer hover cursor to indicate they're links. To open a link, the _Ctrl_ key must be pressed before …

New renderer: HyperlinkRenderer

---

CHANGELOG.md

Automated Changelog Entry for 2021.8.12 on master
Python version: 2021.8.12
npm version: lumino-top-level: 2021.8.3
@lumino/example-datagrid: 0.25.0
@lumino/example-accordionpanel: 0.2.0
@lumino/example-datastore: 0.15.0
@lumino/example-dockpanel: 0.15.0
@lumino/default-theme: 0.17.0
@lumino/application: 1.23.0
@lumino/datagrid: 0.28.0
@lumino/widgets: 1.26.0 …

Automated Changelog Entry for 2021.8.12 on master

---

packages/datagrid/src/datagrid.ts

This PR adds a function which resizes column widths for `body` and `row` column headers (index and non-index columns) based on the text width of their column names. This allows users to not have to worry about manually resizing the grid columns upon instantiation or pre-determine column widths before instantiation. The API is quite simple takes two optional arguments: 
```typescript
DataGrid.fitColumnNames(area: DataGrid.ColumnFitType = 'all', numCols?: number): void;
type ColumnFitType = 'all' | 'row-header' | 'body';
```
`numCols` allow for capping of the number of columns to be resized.

Add auto-resize function for column widths

---

packages/datagrid/src/datagrid.ts

This PR adds an additional `padding` argument to the 'fitColumnNames' function added in #221. This will allow users to control how much padding the resize function will add to a given column text when resizing the column width. The default parameter is 15 pixels.

Add 'padding' argument to fitColumnNames function

---

README.md

Update the README to give a quick idea of what Lumino is.
Add more examples and screencasts too. We should try to add more to the readme or documentation at some point.

Add screencasts and examples to the README

---

CHANGELOG.md

Automated Changelog Entry for 2021.9.22 on master
@lumino/example-datastore: 0.16.0
@lumino/example-accordionpanel: 0.3.0
@lumino/example-dockpanel-iife: 0.2.0
@lumino/example-dockpanel: 0.16.0
@lumino/example-datagrid: 0.27.0
@lumino/example-dockpanel-amd: 0.2.0
@lumino/keyboard: 1.6.0
@lumino/widgets: 1.27.0
@lumino/polling: 1.7.0
@lumino/properties: 1.6.0
@lumino/commands: 1.16.0
@lumino/domutils: 1.6.0
@lumino/signaling: 1.8.0
@lumino/datastore: 0.15.0
@lumino/disposable: 1.8.0
@lumino/collections: 1.7.0
@lumino/datagrid: 0.31.0
@lumino/algorithm: 1.7.0
@lumino/default-theme: 0.18.0
@lumino/coreutils: 1.9.0
@lumino/dragdrop: 1.11.0
@lumino/virtualdom: 1.12.0
@lumino/application: 1.24.0
@lumino/messaging: 1.8.0
After merging this PR run the "Full Release" …

Automated Changelog Entry for 2021.9.22 on master

---

packages/datagrid/src/datagrid.ts

This PR introduces some rendering optimisations by enabling blitting where possible and reducing the number of paint calls for the entire viewport. There is still room for performance tuning, which I'll hopefully have time to explore in the next few weeks.
I also added a helper function `regionHasMergedCells`. It's not used in this PR, but it will be used in the next PR.

Optimise grid rendering

---

.github/jupyterlab-probot.yml
.gitignore
CONTRIBUTING.md
docs/source/conf.py
docs/source/examples.rst
docs/source/index.rst
examples/example-accordionpanel/index.html
examples/example-dockpanel/index.html
package.json
packages/algorithm/tdoptions.json
packages/application/tdoptions.json
packages/collections/tdoptions.json
packages/commands/tdoptions.json
packages/coreutils/tdoptions.json
packages/datagrid/tdoptions.json
packages/datastore/tdoptions.json
packages/disposable/tdoptions.json
packages/domutils/tdoptions.json
packages/dragdrop/tdoptions.json
packages/keyboard/tdoptions.json
packages/messaging/tdoptions.json
packages/polling/tdoptions.json
packages/properties/tdoptions.json
packages/signaling/tdoptions.json
packages/virtualdom/tdoptions.json
packages/widgets/tdoptions.json
typedoc.js

- Add rendered static examples in docs
- Remove the binder link since we could not reliably view the examples in the binder due to iframe limitations

Add static examples in docs

---

CHANGELOG.md

Automated Changelog Entry for 2021.9.30 on master
@lumino/example-datastore: 0.17.0
@lumino/example-accordionpanel: 0.4.0
@lumino/example-dockpanel-iife: 0.3.0
@lumino/example-dockpanel: 0.17.0
@lumino/example-datagrid: 0.28.0
@lumino/example-dockpanel-amd: 0.3.0
@lumino/keyboard: 1.7.0
@lumino/widgets: 1.28.0
@lumino/polling: 1.8.0
@lumino/properties: 1.7.0
@lumino/commands: 1.17.0
@lumino/domutils: 1.7.0
@lumino/signaling: 1.9.0
@lumino/datastore: 0.16.0
@lumino/disposable: 1.9.0
@lumino/collections: 1.8.0
@lumino/datagrid: 0.32.0
@lumino/algorithm: 1.8.0
@lumino/default-theme: 0.19.0
@lumino/coreutils: 1.10.0
@lumino/dragdrop: 1.12.0
@lumino/virtualdom: 1.13.0
@lumino/application: 1.25.0
@lumino/messaging: 1.9.0
After merging this PR run the "Full Release" …

Automated Changelog Entry for 2021.9.30 on master

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts

Fixes #151
Fixes #255
Closes #256
This formats keyboard shortcuts to OS conventions on Windows and macOS. It reverts #252 and supersedes #256.
I checked with VoiceOver, and it appears that these glyphs are recognized correctly on Catalina when speaking shortcuts on menu items, etc. (i.e., the curvy arrow is correctly pronounced "return" when reading the keyboard shortcut). I pulled the Windows formatting conventions by looking at how custom keyboard shortcuts are formatted in Microsoft Word (IIRC), but it would be good to double-check those.

Format keyboard shortcuts according to OS conventions

---

packages/widgets/src/docklayout.ts
packages/widgets/src/dockpanel.ts
packages/widgets/src/stackedlayout.ts
packages/widgets/src/stackedpanel.ts
packages/widgets/src/widget.ts
packages/widgets/tests/src/dockpanel.spec.ts
packages/widgets/tests/src/stackedpanel.spec.ts
packages/widgets/tests/src/widget.spec.ts

Optionally use composition style for high speed tab switch

Use composition to improve tab switch

---

packages/commands/src/index.ts

Introduced in #258, CC @jasongrout

Fix transposed display names for arrow keys

---

CHANGELOG.md

Automated Changelog Entry for 2021.12.13 on main
```
@lumino/example-accordionpanel: 0.6.1
@lumino/example-datagrid: 0.30.1
@lumino/example-datastore: 0.19.1
@lumino/example-dockpanel: 0.19.1
@lumino/application: 1.27.1
@lumino/commands: 1.19.1
@lumino/coreutils: 1.11.1
@lumino/datagrid: 0.34.1
@lumino/datastore: 0.17.1
@lumino/default-theme: 0.20.2
@lumino/dragdrop: 1.13.1
@lumino/polling: 1.9.1
@lumino/widgets: 1.30.1
``` …

Automated Changelog Entry for 2021.12.13 on main

---

packages/widgets/src/docklayout.ts
packages/widgets/src/dockpanel.ts
packages/widgets/src/tabbar.ts
packages/widgets/src/tabpanel.ts

fix(TabBar):  Event forwarding fails when hosted in a ShadowRoot

---

examples/example-dockpanel/src/index.ts
packages/widgets/src/menubar.ts
packages/widgets/tests/src/menubar.spec.ts

Solves https://github.com/jupyterlab/jupyterlab/pull/11650
As commented in https://github.com/jupyterlab/jupyterlab/pull/11650#discussion_r766563571, there is a minor glitch on the menu when it is empty.
This PR prevents the menu bar from adding a menu to the DOM if the menu is empty.

Prevent opening an empty menu

---

packages/widgets/src/widget.ts

Also makes compatible with shadowDom

chore(Widget):  Simplify attach/detach sanity checking

---

CHANGELOG.md

Automated Changelog Entry for 2022.1.10 on main
```
@lumino/example-accordionpanel: 0.7.0
@lumino/example-datagrid: 0.31.0
@lumino/example-datastore: 0.20.0
@lumino/example-dockpanel: 0.20.0
@lumino/application: 1.28.0
@lumino/commands: 1.20.0
@lumino/coreutils: 1.12.0
@lumino/datagrid: 0.35.0
@lumino/datastore: 0.18.0
@lumino/default-theme: 0.21.0
@lumino/dragdrop: 1.14.0
@lumino/polling: 1.10.0
@lumino/widgets: 1.31.0
``` …

Automated Changelog Entry for 2022.1.10 on main

---

packages/widgets/src/docklayout.ts

fix(DockLayout):  Invalid use of "this" in private namespace

---

CHANGELOG.md

Automated Changelog Entry for 2022.1.13 on main
```
@lumino/example-accordionpanel: 0.7.1
@lumino/example-datagrid: 0.31.1
@lumino/example-datastore: 0.20.1
@lumino/example-dockpanel: 0.20.1
@lumino/application: 1.28.1
@lumino/commands: 1.20.0
@lumino/coreutils: 1.12.0
@lumino/datagrid: 0.35.1
@lumino/datastore: 0.18.0
@lumino/default-theme: 0.21.1
@lumino/dragdrop: 1.14.0
@lumino/polling: 1.10.0
@lumino/widgets: 1.31.1
``` …

Automated Changelog Entry for 2022.1.13 on main

---

packages/widgets/src/splitpanel.ts
packages/widgets/tests/src/splitpanel.spec.ts
packages/widgets/tests/src/tabbar.spec.ts

The `handleMoved` signal is useful for capturing state changes in the layout of a `SplitPanel` and saving it (e.g. for layout restoration). This PR allows for removing the following code in JupyterLab:
```typescript
import { ISignal, Signal } from '@lumino/signaling';
import { SplitPanel as SPanel } from '@lumino/widgets';
/**
* A deprecated split panel that will be removed when the phosphor split panel
* supports a handle moved signal. See https://github.com/phosphorjs/phosphor/issues/297.
*/
export class SplitPanel extends SPanel {
/**
* Emits when the split handle has moved.
*/
readonly handleMoved: ISignal<any, void> = new Signal<any, void>(this);
handleEvent(event: Event): void {
super.handleEvent(event);
if (event.type === 'mouseup') {
(this.handleMoved as Signal<any, …
```

Add handle moved signal to split panel

---

packages/widgets/src/accordionpanel.ts
packages/widgets/src/splitlayout.ts
packages/widgets/src/splitpanel.ts
packages/widgets/tests/src/accordionpanel.spec.ts

This PR fixes the sizing issue of the Accordion widget when a child is opened/closed multiple times.
- Add private method `_computeWidgetSize` to `AccordionPanel`  to cache and compute the size of widgets on title click event.
- Add boolean parameter `update`  to `SplitPanel.setRelativeSizes` to allow updating relative size without sending update message to the panel.
- Child widgets keep their sizes after being closed/opened.
- The resize behavior is changed, when a widget is opened or closed, the Accordion panel will try to resize only the last opened widget if possible.
N/A

Fix Accordion sizing issue

---

CHANGELOG.md

Automated Changelog Entry for 2022.6.7 on main
```
@lumino/example-accordionpanel: 0.8.1
@lumino/example-datagrid: 0.32.1
@lumino/example-datastore: 0.21.1
@lumino/example-dockpanel: 0.21.1
@lumino/application: 1.29.1
@lumino/commands: 1.20.0
@lumino/coreutils: 1.12.0
@lumino/datagrid: 0.36.1
@lumino/datastore: 0.18.0
@lumino/default-theme: 0.22.1
@lumino/dragdrop: 1.14.0
@lumino/polling: 1.10.0
@lumino/widgets: 1.32.1
``` …

Automated Changelog Entry for 2022.6.7 on main

---

packages/widgets/src/title.ts
packages/widgets/src/widget.ts
packages/widgets/tests/src/title.spec.ts
packages/widgets/tests/src/widget.spec.ts

When working on adding memory leak test on JupyterLab in that [PR](https://github.com/jupyterlab/benchmarks/pull/100), it was highlighted that the signal connection to `Title.changed` where not cleared when the owner is disposed. This induces a memory leak due to connection stored in `Signal`.
---
In the open/close notebook scenario, the Launcher is removed from the memory leak by commenting the `title.changed` connection in [packages/running-extension/src/opentabs.ts](https://github.com/jupyterlab/jupyterlab/blob/master/packages/running-extension/src/opentabs.ts#L35).
- `Title` implements `IDisposable` and its the responsability of its owner to call `Title.dispose` (as it was added for `Widget` in this PR).

[memory-leak] Title.changed not cleared when owner is disposed

---

CHANGELOG.md

Automated Changelog Entry for 2022.7.21 on main
```
@lumino/example-accordionpanel: 0.8.2
@lumino/example-datagrid: 0.32.2
@lumino/example-datastore: 0.21.2
@lumino/example-dockpanel: 0.21.2
@lumino/application: 1.29.2
@lumino/commands: 1.20.0
@lumino/coreutils: 1.12.0
@lumino/datagrid: 0.36.2
@lumino/datastore: 0.18.0
@lumino/default-theme: 0.22.2
@lumino/dragdrop: 1.14.0
@lumino/polling: 1.11.0
@lumino/widgets: 1.33.0
``` …

Automated Changelog Entry for 2022.7.21 on main

---

packages/widgets/src/accordionpanel.ts
packages/widgets/tests/src/accordionpanel.spec.ts

Required for https://github.com/jupyterlab/jupyterlab/pull/12866
Add API to programmatically expand or collapse a `AccordionPanel` widget. Before only user by clicking on the title could do that.
It is required for the extensions manager so we can show or hide the warning about installing third-party extensions depending on a settings parameter.

Add `collapse` and `expand` methods to `AccordionPanel`

---

packages/widgets/src/splitpanel.ts
packages/widgets/tests/src/splitpanel.spec.ts

Continuation of Lumino 2 deprecated code removal: this PR removes mouse event handlers from `SplitPanel` and leaves only pointer event handlers.

Remove mouse event handlers from SplitPanel

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts

Follow-up of https://github.com/jupyterlab/lumino/pull/322#issuecomment-1205383882
cc @bollwyvl

Allow describedBy to be an async function

---

CHANGELOG.md

Automated Changelog Entry for 2022.8.8 on 1.x
```
@lumino/example-accordionpanel: 0.8.3
@lumino/example-datagrid: 0.32.3
@lumino/example-datastore: 0.21.3
@lumino/example-dockpanel: 0.21.3
@lumino/application: 1.29.3
@lumino/collections: 1.9.2
@lumino/commands: 1.20.1
@lumino/datagrid: 0.36.3
@lumino/datastore: 0.18.1
@lumino/default-theme: 0.22.3
@lumino/disposable: 1.10.2
@lumino/dragdrop: 1.14.1
@lumino/messaging: 1.10.2
@lumino/polling: 1.11.1
@lumino/signaling: 1.10.2
@lumino/virtualdom: 1.14.2
@lumino/widgets: 1.34.0
``` …

Automated Changelog Entry for 2022.8.8 on 1.x

---

packages/algorithm/package.json
packages/application/package.json
packages/collections/package.json
packages/commands/package.json
packages/coreutils/package.json
packages/datagrid/package.json
packages/default-theme/package.json
packages/disposable/package.json
packages/domutils/package.json
packages/dragdrop/package.json
packages/keyboard/package.json
packages/messaging/package.json
packages/polling/package.json
packages/properties/package.json
packages/signaling/package.json
packages/virtualdom/package.json
packages/widgets/package.json

This PR updates all of the `author` fields in the `package.json` files for each published Lumino package to be set to `Project Jupyter`.

Update NPM package author to Project Jupyter

---

.github/codeql/codeql-config.yml
.github/dependabot.yml
.github/workflows/auto-author-assign.yml
.github/workflows/check-api-changes.yml
.github/workflows/codeql-analysis.yml
.github/workflows/license-header.yml
.github/workflows/lock.yml
.licenserc.yaml
api-extractor-base.json
review/api/algorithm.api.md
review/api/application.api.md
review/api/collections.api.md
review/api/commands.api.md
review/api/coreutils.api.md
review/api/datagrid.api.md
review/api/disposable.api.md
review/api/dragdrop.api.md
review/api/keyboard.api.md
review/api/messaging.api.md
review/api/polling.api.md
review/api/properties.api.md
review/api/signaling.api.md
review/api/virtualdom.api.md
review/api/widgets.api.md

Workflows added:
- PR auto author assignment
- Check API changes - if the changes are valid, the PR author will need to explicitly update the files
- CodeQL analysis
- License header
- Lock resolved threads
I decided to ignore the only CodeQL error: https://github.com/jupyterlab/lumino/security/code-scanning/1
> First commit is expected to fail as the extracted API is not up-to-date.

Add more safety workflows

---

docs/source/migration.md
packages/dragdrop/src/index.ts
packages/dragdrop/tests/src/index.spec.ts
packages/widgets/src/dockpanel.ts
review/api/dragdrop.api.md

- This PR updates `@lumino/dragdrop` to use [`new PointerEvent(...)`](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) instances or sub-classes of `DragEvent` instead of [initMouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent), which is deprecated.
- This PR **moves** the `DropAction` and `SupportedActions` type definitions into the `Drag` namespace. This does not seem to affect any downstream Lumino or JupyterLab code.
- This PR **deprecates** the `IDragEvent` interface and suggests client code use `Drag.Event` instead.
Fixes https://github.com/jupyterlab/lumino/issues/353
Partially fixes https://github.com/jupyterlab/lumino/issues/340
| | `export` | name | note |
|-|-|-|-|
| ❌ | `type` | `DropAction` | Moved to `Drag.DropAction` |
| ❌ | …

Update `dragdrop` to use `PointerEvent` and `DragEvent`

---

CHANGELOG.md

Automated Changelog Entry for 2022.8.22-alpha.0 on main
```
@lumino/example-accordionpanel: 0.9.0-alpha.0
@lumino/example-datagrid: 0.33.0-alpha.0
@lumino/example-dockpanel: 0.22.0-alpha.0
@lumino/example-dockpanel-amd: 0.5.0-alpha.0
@lumino/example-dockpanel-iife: 0.5.0-alpha.0
@lumino/algorithm: 2.0.0-alpha.0
@lumino/application: 2.0.0-alpha.0
@lumino/collections: 2.0.0-alpha.0
@lumino/commands: 2.0.0-alpha.0
@lumino/coreutils: 2.0.0-alpha.0
@lumino/datagrid: 1.0.0-alpha.0
@lumino/default-theme: 1.0.0-alpha.0
@lumino/disposable: 2.0.0-alpha.0
@lumino/domutils: 2.0.0-alpha.0
@lumino/dragdrop: 2.0.0-alpha.0
@lumino/keyboard: 2.0.0-alpha.0
@lumino/messaging: 2.0.0-alpha.0
@lumino/polling: 2.0.0-alpha.0
@lumino/properties: 2.0.0-alpha.0
@lumino/signaling: …
```

Automated Changelog Entry for 2022.8.22-alpha.0 on main

---

package.json

All v2 alpha.0 versions have been deprecated as they were published on default npm tag. Hopefully we can get the final version out quickly so the [warning](https://www.npmjs.com/package/@lumino/algorithm) on the default package page disappears...
Once this is merged, I will carry out a new alpha release.

Set npm tag to next for prerelease

---

packages/algorithm/src/iter.ts
packages/algorithm/src/retro.ts
packages/algorithm/tests/src/iter.spec.ts
packages/algorithm/tests/src/retro.spec.ts
packages/collections/src/linkedlist.ts

Follow on to https://github.com/jupyterlab/lumino/pull/346

Refactor `retro()`, clean up iterators

---

CHANGELOG.md

Automated Changelog Entry for 2022.8.22-alpha.1 on main
```
@lumino/example-accordionpanel: 0.9.0-alpha.1
@lumino/example-datagrid: 0.33.0-alpha.1
@lumino/example-dockpanel: 0.22.0-alpha.1
@lumino/example-dockpanel-amd: 0.5.0-alpha.1
@lumino/example-dockpanel-iife: 0.5.0-alpha.1
@lumino/algorithm: 2.0.0-alpha.1
@lumino/application: 2.0.0-alpha.1
@lumino/collections: 2.0.0-alpha.1
@lumino/commands: 2.0.0-alpha.1
@lumino/coreutils: 2.0.0-alpha.1
@lumino/datagrid: 1.0.0-alpha.1
@lumino/default-theme: 1.0.0-alpha.1
@lumino/disposable: 2.0.0-alpha.1
@lumino/domutils: 2.0.0-alpha.1
@lumino/dragdrop: 2.0.0-alpha.1
@lumino/keyboard: 2.0.0-alpha.1
@lumino/messaging: 2.0.0-alpha.1
@lumino/polling: 2.0.0-alpha.1
@lumino/properties: 2.0.0-alpha.1
@lumino/signaling: …
```

Automated Changelog Entry for 2022.8.22-alpha.1 on main

---

README.md
packages/widgets/src/menubar.ts
packages/widgets/tests/src/menubar.spec.ts

There are a few tab traps in the JupyterLab UI. The worst offender is the top menu bar. The code change in this pull request is the most straightforward way to fix the menu bar tab trap in JupyterLab.
In terms of backwards compatibility, I have a hard time imagining that downstream dependents on Lumino would rely on the tab key event getting caught and swallowed (`event.preventDefault` + `event.stopPropagation`) by the Lumino menu bar, but it is something to consider.

Fix tab trap in menubar

---

packages/application/src/index.ts
packages/application/tests/src/index.spec.ts
packages/application/tests/tsconfig.json
packages/commands/src/index.ts
review/api/application.api.md

Fixes #278
There are three additions to the API :
- `Application.unregisterPlugin()` method to remove the plugin from the plugin map and complement the existing `registerPlugin()`
- an optional `deactivate` method which plugins may decide to implement. If it is provided, it should undo all the changes the `activate` method made, including removing the added commands, menus, etc. to complement the current [`activate()`](https://github.com/jupyterlab/lumino/blob/578509cae6af5567975a6ed2e6bc9d8a1927a078/packages/application/src/index.ts#L84-L101) method.
- `Application.deactivatePlugin` method to call the `deactivate` method on the plugin and all of it dependants
The `unregisterPlugin` signature is:
```typescript
/**
* @param id - id of the plugin to unregister
* @param force - whether to …
```

Dynamic extensions reloading

---

CHANGELOG.md

Automated Changelog Entry for 2022.8.29 on main
```
@lumino/example-accordionpanel: 0.9.0-alpha.2
@lumino/example-datagrid: 0.33.0-alpha.2
@lumino/example-dockpanel: 0.22.0-alpha.2
@lumino/example-dockpanel-amd: 0.5.0-alpha.2
@lumino/example-dockpanel-iife: 0.5.0-alpha.2
@lumino/algorithm: 2.0.0-alpha.2
@lumino/application: 2.0.0-alpha.2
@lumino/collections: 2.0.0-alpha.2
@lumino/commands: 2.0.0-alpha.2
@lumino/coreutils: 2.0.0-alpha.2
@lumino/datagrid: 1.0.0-alpha.2
@lumino/default-theme: 1.0.0-alpha.2
@lumino/disposable: 2.0.0-alpha.2
@lumino/domutils: 2.0.0-alpha.2
@lumino/dragdrop: 2.0.0-alpha.2
@lumino/keyboard: 2.0.0-alpha.2
@lumino/messaging: 2.0.0-alpha.2
@lumino/polling: 2.0.0-alpha.2
@lumino/properties: 2.0.0-alpha.2
@lumino/signaling: 2.0.0-alpha.2 …
```

Automated Changelog Entry for 2022.8.29 on main

---

CHANGELOG.md

Automated Changelog Entry for 2022.8.30 on main
```
@lumino/example-accordionpanel: 0.9.0-alpha.3
@lumino/example-datagrid: 0.33.0-alpha.3
@lumino/example-dockpanel: 0.22.0-alpha.3
@lumino/example-dockpanel-amd: 0.5.0-alpha.3
@lumino/example-dockpanel-iife: 0.5.0-alpha.3
@lumino/algorithm: 2.0.0-alpha.3
@lumino/application: 2.0.0-alpha.3
@lumino/collections: 2.0.0-alpha.3
@lumino/commands: 2.0.0-alpha.3
@lumino/coreutils: 2.0.0-alpha.3
@lumino/datagrid: 1.0.0-alpha.3
@lumino/default-theme: 1.0.0-alpha.3
@lumino/disposable: 2.0.0-alpha.3
@lumino/domutils: 2.0.0-alpha.3
@lumino/dragdrop: 2.0.0-alpha.3
@lumino/keyboard: 2.0.0-alpha.3
@lumino/messaging: 2.0.0-alpha.3
@lumino/polling: 2.0.0-alpha.3
@lumino/properties: 2.0.0-alpha.3
@lumino/signaling: 2.0.0-alpha.3 …
```

Automated Changelog Entry for 2022.8.30 on main

---

CHANGELOG.md
packages/polling/README.md
packages/polling/src/index.ts
packages/polling/src/poll.ts
packages/polling/tests/src/poll.spec.ts
packages/polling/tests/tsconfig.json
review/api/polling.api.md

In this PR, the `IPoll` interface and the `Poll` class extend `AsyncIterable` (by implementing a [`Symbol.asyncIterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator) method) to support [`for-await...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) loops.
This PR also adds a `README.md` file for the `@lumino/polling` package.
This functionality may be a natural fit for streams of events from the new [Jupyter event system](https://github.com/jupyter-server/jupyter_server/issues/780), other `WebSocket` connections, or other stream sources.
cc: @Zsailer @andrii-i @davidbrochart @3coins @vidartf (since you all have some interest in events and/or iterators)
---
The tests in this PR are …

Make `Poll` an async iterable

---

.github/workflows/enforce-label.yml
.github/workflows/license-header.yml

Write permission cannot be granted to `pull_request` event from forks.
This uses `pull_request_target` to fix the CI jobs.
See [documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)

Use `pull_request_target` to have write access on fork

---

packages/application/src/index.ts
packages/application/tests/src/index.spec.ts

This  makes the current version of `@lumino/application` unusable.

Fix bug that prevents any startup plugins from activating

---

CHANGELOG.md

Automated Changelog Entry for 2022.9.6 on main
```
@lumino/example-accordionpanel: 0.9.0-alpha.4
@lumino/example-datagrid: 0.33.0-alpha.4
@lumino/example-dockpanel: 0.22.0-alpha.4
@lumino/example-dockpanel-amd: 0.5.0-alpha.3
@lumino/example-dockpanel-iife: 0.5.0-alpha.3
@lumino/algorithm: 2.0.0-alpha.4
@lumino/application: 2.0.0-alpha.4
@lumino/collections: 2.0.0-alpha.4
@lumino/commands: 2.0.0-alpha.4
@lumino/coreutils: 2.0.0-alpha.4
@lumino/datagrid: 1.0.0-alpha.4
@lumino/default-theme: 1.0.0-alpha.4
@lumino/disposable: 2.0.0-alpha.4
@lumino/domutils: 2.0.0-alpha.4
@lumino/dragdrop: 2.0.0-alpha.4
@lumino/keyboard: 2.0.0-alpha.4
@lumino/messaging: 2.0.0-alpha.4
@lumino/polling: 2.0.0-alpha.4
@lumino/properties: 2.0.0-alpha.4
@lumino/signaling: 2.0.0-alpha.4 …
```

Automated Changelog Entry for 2022.9.6 on main

---

packages/polling/src/poll.ts

As noted on issue #392, using `requestAnimationFrame` means that no deferred tasks can take place while the user has the browser window in the background. This can lead to a bad experience for long-lasting tasks, particularly setup tasks (when a user might start JupyterLab, switch somewhere else when it loads, and then come back).
This change instead uses `setTimeout` (with a timeout of zero, either implicitly or explicitly), which immediately puts the task on the event loop to be run (subject to less severe browser throttling). This allows these tasks to occur in the background (and should hopefully not be too taxing on user resources).
https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#timeouts_in_inactive_tabs
> Firefox Desktop and Chrome both have a minimum timeout of 1 …

Switch to using `setTimeout` for all deferred processing.

---

CHANGELOG.md

Automated Changelog Entry for 2022.9.9-alpha.5 on main
```
@lumino/example-accordionpanel: 0.9.0-alpha.5
@lumino/example-datagrid: 0.33.0-alpha.5
@lumino/example-dockpanel: 0.22.0-alpha.5
@lumino/example-dockpanel-amd: 0.5.0-alpha.3
@lumino/example-dockpanel-iife: 0.5.0-alpha.3
@lumino/algorithm: 2.0.0-alpha.5
@lumino/application: 2.0.0-alpha.5
@lumino/collections: 2.0.0-alpha.5
@lumino/commands: 2.0.0-alpha.5
@lumino/coreutils: 2.0.0-alpha.5
@lumino/datagrid: 1.0.0-alpha.5
@lumino/default-theme: 1.0.0-alpha.5
@lumino/disposable: 2.0.0-alpha.5
@lumino/domutils: 2.0.0-alpha.5
@lumino/dragdrop: 2.0.0-alpha.5
@lumino/keyboard: 2.0.0-alpha.5
@lumino/messaging: 2.0.0-alpha.5
@lumino/polling: 2.0.0-alpha.5
@lumino/properties: 2.0.0-alpha.5
@lumino/signaling: …
```

Automated Changelog Entry for 2022.9.9-alpha.5 on main

---

packages/widgets/src/accordionpanel.ts
packages/widgets/src/tabbar.ts
review/api/widgets.api.md

The title id for accordion panel and tabbar were not unique if multiple widgets were displayed on the same page. This fixes it.

Fix labelledby to support multiple elements on page

---

packages/widgets/src/accordionpanel.ts
packages/widgets/src/tabbar.ts

Backport PR #407 on branch 1.x (Fix labelledby to support multiple elements on page)

---

examples/example-accordionpanel/index.html
examples/example-datagrid/index.html
examples/example-dockpanel-amd/index.html
examples/example-dockpanel-iife/index.html
examples/example-dockpanel/index.html
packages/widgets/src/docklayout.ts
packages/widgets/src/dockpanel.ts
packages/widgets/tests/src/docklayout.spec.ts
packages/widgets/tests/src/dockpanel.spec.ts

This PR:
- Fixes resizing in `DockPanel`
- Fixes switching between `single-document` and `multiple-document` in `DockLayout`
- Fixes the broken shortcut characters in the example pages
- Adds an empty test to the `docklayout.spec.ts` file
This came up in the Lumino Gitter channel:
https://gitter.im/jupyterlab/lumino?at=6321ba7faa091774290be83a

Fix resizing and mode switching in `DockPanel`

---

CHANGELOG.md

Automated Changelog Entry for 2022.9.15-alpha.6 on main
```
@lumino/example-accordionpanel: 0.9.0-alpha.6
@lumino/example-datagrid: 0.33.0-alpha.6
@lumino/example-dockpanel: 0.22.0-alpha.6
@lumino/example-dockpanel-amd: 0.5.0-alpha.6
@lumino/example-dockpanel-iife: 0.5.0-alpha.6
@lumino/algorithm: 2.0.0-alpha.6
@lumino/application: 2.0.0-alpha.6
@lumino/collections: 2.0.0-alpha.6
@lumino/commands: 2.0.0-alpha.6
@lumino/coreutils: 2.0.0-alpha.6
@lumino/datagrid: 1.0.0-alpha.6
@lumino/default-theme: 1.0.0-alpha.6
@lumino/disposable: 2.0.0-alpha.6
@lumino/domutils: 2.0.0-alpha.6
@lumino/dragdrop: 2.0.0-alpha.6
@lumino/keyboard: 2.0.0-alpha.6
@lumino/messaging: 2.0.0-alpha.6
@lumino/polling: 2.0.0-alpha.6
@lumino/properties: 2.0.0-alpha.6
@lumino/signaling: …
```

Automated Changelog Entry for 2022.9.15-alpha.6 on main

---

docs/source/migration.md
packages/algorithm/src/empty.ts
packages/widgets/src/docklayout.ts
review/api/algorithm.api.md

This PR:
- adds a section in the migration guide for `yield*` usage
- un-deprecates `empty()`
cc: @vidartf, you might find this and https://github.com/jupyterlab/lumino/pull/411 interesting

Follow on to #411 addressing `yield*`

---

examples/example-datagrid/src/index.ts
packages/datagrid/src/cellgroup.ts
packages/datagrid/src/datagrid.ts
review/api/datagrid.api.md

cc. @ibdafna 
This PR improves the performance of the grid by reworking the drawing of merged cells logic.
- Before (resizing/scrolling a 1M cells grid with merged cells freezes):
https://user-images.githubusercontent.com/21197331/188858914-860b06bf-4005-4439-9814-93150ee4e5cc.mp4
- After (resizing/scrolling a 1M cells grid with merged cells works smoothly):
https://user-images.githubusercontent.com/21197331/188859052-f09e20a2-dac7-46a4-b985-4b9cbaf0238e.mp4
Note for the tester: You will see a big difference in performance if you zoom out a lot and show a lot of cells.

Improve datagrid performance

---

docs/environment.yml
docs/source/conf.py

Switch to pydata sphinx theme

---

packages/collections/src/bplustree.ts
packages/dragdrop/src/index.ts

This PR is listed among tasks for JupyterLab 3.5.0: https://github.com/jupyterlab/jupyterlab/issues/13064

Add deprecation warnings

---

CHANGELOG.md

Automated Changelog Entry for 2022.10.5 on 1.x
```
@lumino/example-accordionpanel: 0.8.4
@lumino/example-datagrid: 0.32.4
@lumino/example-datastore: 0.21.4
@lumino/example-dockpanel: 0.21.4
@lumino/application: 1.29.4
@lumino/commands: 1.20.1
@lumino/datagrid: 0.36.4
@lumino/datastore: 0.18.2
@lumino/default-theme: 0.22.4
@lumino/disposable: 1.10.2
@lumino/dragdrop: 1.14.2
@lumino/polling: 1.11.2
@lumino/signaling: 1.10.2
@lumino/virtualdom: 1.14.2
@lumino/widgets: 1.34.1
``` …

Automated Changelog Entry for 2022.10.5 on 1.x

---

packages/widgets/tests/src/docklayout.spec.ts

Add DockLayout tests

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts
packages/widgets/src/commandpalette.ts
packages/widgets/src/menu.ts
review/api/commands.api.md

Xref: https://github.com/jupyterlab/jupyterlab/issues/13180
Support passing a list of keys to `Command.formatKeystroke` to get a comma-separated representation as the one used in menus.

Add support for list of keystrokes

---

packages/signaling/package.json
packages/signaling/src/index.ts
packages/signaling/tests/src/index.spec.ts
review/api/signaling.api.md

Add blocking signal feature - this inspired by the [Qt signal API](https://doc.qt.io/qt-6/qobject.html#blockSignals).
Use cases are:
- To reset an object to a given state
- When you are synchronizing two objects, you need to temporary break the signal loop (this is the primary goal to ease code clarity for synchronizing modelDB and shared models).
It will block signal emission for the duration of a synchronous callback
Add 
- `ISignal.block(callback: () => void): void` to block a single signal during a callback execution
- and `Signal.blockAll(sender, callback: () => void): void` to block all signals during a callback execution from a given sender.

Add blocking signal feature

---

packages/datagrid/src/basicmousehandler.ts
packages/datagrid/src/datagrid.ts

The Datagrid was always preventing the propagation of the wheel event, preventing the scrolling of the page when using the wheel on top of a grid that does not need scrolling. This PR fixes it by only stopping the propagation if the grid actually needs scrolling.
cc. @ibdafna 
https://user-images.githubusercontent.com/21197331/196924993-bb0c246d-e598-4597-b30e-5c80684f264a.mp4

Datagrid: Do not prevent page scroll if we are not actually scrolling the grid

---

CHANGELOG.md

Automated Changelog Entry for 2022.10.31 on 1.x
```
@lumino/example-accordionpanel: 0.8.5
@lumino/example-datagrid: 0.32.5
@lumino/example-datastore: 0.21.5
@lumino/example-dockpanel: 0.21.5
@lumino/application: 1.30.0
@lumino/commands: 1.21.0
@lumino/datagrid: 0.36.5
@lumino/datastore: 0.18.3
@lumino/default-theme: 0.22.5
@lumino/disposable: 1.10.3
@lumino/dragdrop: 1.14.3
@lumino/polling: 1.11.3
@lumino/signaling: 1.11.0
@lumino/virtualdom: 1.14.3
@lumino/widgets: 1.35.0
``` …

Automated Changelog Entry for 2022.10.31 on 1.x

---

packages/datagrid/src/hyperlinkrenderer.ts
packages/datagrid/src/textrenderer.ts
review/api/datagrid.api.md

Disable text eliding by default

---

packages/signaling/package.json
packages/signaling/src/index.ts
packages/signaling/tests/src/index.spec.ts
review/api/signaling.api.md

This PR adds a `Stream` class that `extends Signal` and implements `IStream`, which means that in addition to being a signal, it is also an async iterable. It can be used as a drop-in replacement for any `Signal` (or `ISignal`) in an application if the author wishes to expose an async iterable API to complement signal connection/disconnection.
This PR also exposes a `protected blocked: number` property of a `Signal` so that sub-classes can implement correct blocking behavior.
```ts
// Instantiate a stream.
const stream = new Stream<unknown, string>({});
// Connect a handler to the stream.
const handler = (_, args) => console.log(`emission is: ${args}`);
stream.connect(handler);
stream.emit('foo');
// [OUTPUT] emission is: foo
stream.emit('bar');
// [OUTPUT] emission is: bar …
```

Add async iterable `Stream` class that inherits from `Signal`

---

packages/signaling/src/index.ts

This is a minor bug that might manifest in testing suites or in circumstances where a `Stream` instance is stopped when nobody is subscribed to its async iterator.

When rejecting the internal promise in a `Stream`, catch failures

---

.github/workflows/license-header.yml
examples/example-menubar/index.html
examples/example-menubar/package.json
examples/example-menubar/rollup.config.js
examples/example-menubar/src/index.ts
examples/example-menubar/style/content.css
examples/example-menubar/style/index.css
examples/example-menubar/tsconfig.json
packages/widgets/src/menubar.ts
packages/widgets/tests/src/menubar.spec.ts
review/api/widgets.api.md

This PR will improve accessibility issues with the menubar component, bringing it closer to being WCAG2.1 compliant. In particular it will
* Set the tabindex properties as specified;
* Handle the focus setting as specified, both when focus first moves into the menubar and also when focus moves out of it;
This is my first bit of work with the lumino codebase, so all comments, particularly around architecture are much appreciated.
I haven't added any tests yet, that is the next step.

Improve the menubar accessibility

---

examples/example-nested-dockpanel-amd/README.md
examples/example-nested-dockpanel-amd/index.html
examples/example-nested-dockpanel-amd/package.json
examples/example-nested-dockpanel-amd/src/index.js
examples/example-nested-dockpanel-amd/style/content.css
examples/example-nested-dockpanel-amd/style/index.css
examples/example-nested-dockpanel-amd/test/runner.js
packages/widgets/src/dockpanel.ts

This pull request applies the proposed solution to issue #472, by allowing drag events to be propagated when the current potential docking position is invalid.
Here you can see an animation of the solved problem.

Fix drag-and-drop of nested dock panel

---

CHANGELOG.md

Automated Changelog Entry for 2022.11.29 on 1.x
```
@lumino/example-accordionpanel: 0.8.5
@lumino/example-datagrid: 0.32.5
@lumino/example-datastore: 0.21.5
@lumino/example-dockpanel: 0.21.5
@lumino/example-menubar: 0.1.0-alpha.0
@lumino/example-nested-dockpanel-amd: 0.4.0
@lumino/application: 1.30.0
@lumino/commands: 1.21.0
@lumino/datagrid: 0.36.5
@lumino/datastore: 0.18.3
@lumino/default-theme: 0.22.5
@lumino/disposable: 1.10.3
@lumino/dragdrop: 1.14.3
@lumino/polling: 1.11.3
@lumino/signaling: 1.11.0 …
```

Automated Changelog Entry for 2022.11.29 on 1.x

---

.github/workflows/tests.yml
packages/algorithm/tests/karma.conf.js
packages/application/tests/karma.conf.js
packages/collections/tests/karma.conf.js
packages/commands/tests/karma.conf.js
packages/coreutils/tests/karma.conf.js
packages/disposable/tests/karma.conf.js
packages/domutils/tests/karma.conf.js
packages/dragdrop/tests/karma.conf.js
packages/keyboard/tests/karma.conf.js
packages/messaging/tests/karma.conf.js
packages/polling/tests/karma.conf.js
packages/properties/tests/karma.conf.js
packages/signaling/tests/karma.conf.js
packages/virtualdom/tests/karma.conf.js
packages/widgets/tests/karma.conf.js

This fixes the CI failure of Firefox not found on Ubuntu
I also added the tests against webkit on Windows and mac - unfortunately the Playwright webkit binary is not directly compatible with the ubuntu image. So I'm skipping it for now.

Use Firefox from playwright

---

CHANGELOG.md
api-extractor-base.json
examples/example-accordionpanel/package.json
examples/example-datagrid/package.json
examples/example-datastore/package.json
examples/example-dockpanel/package.json
examples/example-menubar/package.json
examples/example-nested-dockpanel-amd/package.json
packages/application/package.json
packages/datagrid/package.json
packages/default-theme/package.json
packages/widgets/package.json
packages/widgets/src/menubar.ts
review/api/algorithm.api.md
review/api/application.api.md
review/api/collections.api.md
review/api/commands.api.md
review/api/coreutils.api.md
review/api/datagrid.api.md
review/api/datastore.api.md
review/api/disposable.api.md
review/api/dragdrop.api.md
review/api/keyboard.api.md
review/api/polling.api.md
review/api/virtualdom.api.md
review/api/widgets.api.md

- Fix additional `tabbable` to be optional for backward compatibility
- Remove changelog from unpublished version

Bump version

---

packages/application/src/index.ts

When trying to use it in `jupyterlab-plugin-playground` with JupyterLab 3.6.0-alpha.5. I realized the number of packages brings errors when linearizing the package dependency graph.
This filters the list of dependency relationship to the minimal graph related to the plugin to be deactivated.

Fix finding dependents for deactivation

---

packages/widgets/src/docklayout.ts
packages/widgets/src/widget.ts
packages/widgets/tests/src/widget.spec.ts
review/api/widgets.api.md

See https://github.com/jupyterlab/lumino/issues/496#issuecomment-1363431726.
Once support for content-visibility is better across browsers we should make it the default as we have exactly the use case that it was intended for (see point two in [specification](https://www.w3.org/TR/css-contain-2/#using-cv-hidden)).
Performance-wise, I re-run the benchmark for three tabs (as in the issue: two test notebooks and launcher) after full integration and it works as expected:
Google Chrome 108
| hidden mode |IQM [Q1 - Q3] | mean | min |
|----|---|---|---|
| display | 3043.3 [2944.3 – 3193.1] ms | 3051.3 ms | 2390.9 ms
| content-visibility | 631.6 [606.4 – 694.6] ms | 687.7 ms | 566.5 ms
| scale | 548.6 [531 – 561.3] ms | 566.2 ms | 506.6 ms |
but differently to `scale`, it does not cause …

Add content-visibility hide mode

---

packages/widgets/src/cssPatch.d.ts
packages/widgets/src/docklayout.ts
packages/widgets/src/widget.ts
packages/widgets/tests/src/cssPatch.d.ts
packages/widgets/tests/src/widget.spec.ts
review/api/widgets.api.md

Backport PR https://github.com/jupyterlab/lumino/pull/497 on branch 1.x (Add content-visibility hide mode)

Backport PR #497 on branch 1.x (Add content-visibility hide mode)

---

packages/widgets/src/accordionpanel.ts
packages/widgets/src/commandpalette.ts

Related to https://github.com/jupyter/notebook/issues/6671.
Changes the roles of (1) accordion title and (2) toggleable items of command palette according to the [W3C recommendation ](https://www.w3.org/TR/wai-aria-1.1/#widget_roles).

Accessibility: role attributes

---

packages/widgets/src/accordionlayout.ts
packages/widgets/src/docklayout.ts
packages/widgets/src/dockpanel.ts
packages/widgets/src/layout.ts
packages/widgets/src/splitlayout.ts

Closes https://github.com/jupyterlab/lumino/issues/504
Uses strict CSS containment on elements with fully managed layout (absolutely positioned elements that specify all coordinates and dimensions, e.g. top + left + width + height, or top + left + bottom + right) to reduce layout cost (improves performance for resizing certain elements and other actions).
This requires that nothing within the widgets paints outside of it. Some modest changes may be needed downstream to remove painting outside of the widget box, as in https://github.com/jupyterlab/jupyterlab/pull/13671.
The added contain can be overridden in sub-classes of `LayoutItem`.
I would suggest that we merge this, cut a release, pull it in JupyterLab and run full test suite (once https://github.com/jupyterlab/jupyterlab/pull/13671 …

Add contain strict for elements with fully managed layout

---

packages/dragdrop/src/index.ts
packages/dragdrop/style/index.css
packages/dragdrop/tests/src/index.spec.ts

Fixes #450:
- improves performance of the drag image by moving its positioning to compositor (`transform: translate`, `will-change`)
- works around Chromium [Issue 664066](https://bugs.chromium.org/p/chromium/issues/detail?id=664066) by using a custom backdrop node which is dynamically positioned behind the cursor and hidden with high-performance z-index change for hit testing.
Results having `gh-9757-reproducer.ipynb` (n=50000) open on the side and:
| Before | After |
|---|---|
| ![Screenshot from 2022-12-26 04-28-08](https://user-images.githubusercontent.com/5832902/209500227-bb4ad89c-3599-47bc-9755-f08557235074.png) | ![Screenshot from 2022-12-26 04-30-20](https://user-images.githubusercontent.com/5832902/209500192-7f79176e-c86c-49d3-889b-8ae183941e89.png) |
| Before | After | …

Improve performance of drag & drop, esp. in Chrome

---

CHANGELOG.md

Automated Changelog Entry for 2023.1.3-alpha.7 on main
```
@lumino/example-accordionpanel: 2.0.0-alpha.7
@lumino/example-datagrid: 2.0.0-alpha.7
@lumino/example-dockpanel: 2.0.0-alpha.7
@lumino/example-dockpanel-amd: 2.0.0-alpha.7
@lumino/example-dockpanel-iife: 2.0.0-alpha.7
@lumino/example-menubar: 0.1.0-alpha.7
@lumino/example-nested-dockpanel-amd: 2.0.0-alpha.7
@lumino/algorithm: 2.0.0-alpha.7
@lumino/application: 2.0.0-alpha.7
@lumino/collections: 2.0.0-alpha.7
@lumino/commands: 2.0.0-alpha.7
@lumino/coreutils: 2.0.0-alpha.7
@lumino/datagrid: 2.0.0-alpha.7
@lumino/default-theme: 2.0.0-alpha.7
@lumino/disposable: 2.0.0-alpha.7
@lumino/domutils: 2.0.0-alpha.7
@lumino/dragdrop: 2.0.0-alpha.7
@lumino/keyboard: 2.0.0-alpha.7
@lumino/messaging: 2.0.0-alpha.7 …
```

Automated Changelog Entry for 2023.1.3-alpha.7 on main

---

packages/widgets/src/widget.ts

Fixes #499. I would appreciate a review from someone working on accessibility.

Only add aria-hidden for `scale` mode

---

CHANGELOG.md

Automated Changelog Entry for 2023.1.13-beta.0 on main
```
@lumino/buildutils: 2.0.0-beta.0
@lumino/example-accordionpanel: 2.0.0-beta.0
@lumino/example-datagrid: 2.0.0-beta.0
@lumino/example-dockpanel: 2.0.0-beta.0
@lumino/example-dockpanel-amd: 2.0.0-beta.0
@lumino/example-dockpanel-iife: 2.0.0-beta.0
@lumino/example-menubar: 2.0.0-beta.0
@lumino/example-nested-dockpanel-amd: 2.0.0-beta.0
@lumino/algorithm: 2.0.0-beta.0
@lumino/application: 2.0.0-beta.0
@lumino/collections: 2.0.0-beta.0
@lumino/commands: 2.0.0-beta.0
@lumino/coreutils: 2.0.0-beta.0
@lumino/datagrid: 2.0.0-beta.0
@lumino/default-theme: 2.0.0-beta.0
@lumino/disposable: 2.0.0-beta.0
@lumino/domutils: 2.0.0-beta.0
@lumino/dragdrop: 2.0.0-beta.0
@lumino/keyboard: 2.0.0-beta.0
@lumino/messaging: …
```

Automated Changelog Entry for 2023.1.13-beta.0 on main

---

packages/signaling/src/index.ts

https://github.com/jupyterlab/lumino/pull/444#issuecomment-1400395192
Add deprecation warning on `[I]Signal.block` and `Signal.blockAll`
Make `ISignal.block` optional

Add deprecation warning on Signal blocking feature

---

CHANGELOG.md

Automated Changelog Entry for 2023.1.23 on 1.x
```
@lumino/example-accordionpanel: 0.8.8
@lumino/example-datagrid: 0.32.8
@lumino/example-datastore: 0.21.8
@lumino/example-dockpanel: 0.21.8
@lumino/example-menubar: 0.1.3
@lumino/example-nested-dockpanel-amd: 0.4.1
@lumino/application: 1.31.3
@lumino/commands: 1.21.1
@lumino/datagrid: 0.36.8
@lumino/datastore: 0.18.4
@lumino/default-theme: 0.22.8
@lumino/disposable: 1.10.4
@lumino/dragdrop: 1.14.4
@lumino/polling: 1.11.4
@lumino/signaling: 1.11.1
@lumino/virtualdom: …
```

Automated Changelog Entry for 2023.1.23 on 1.x

---

CHANGELOG.md

Automated Changelog Entry for 2023.1.24-beta.1 on main
```
@lumino/buildutils: 2.0.0-beta.0
@lumino/example-accordionpanel: 2.0.0-beta.1
@lumino/example-datagrid: 2.0.0-beta.1
@lumino/example-dockpanel: 2.0.0-beta.1
@lumino/example-dockpanel-amd: 2.0.0-beta.0
@lumino/example-dockpanel-iife: 2.0.0-beta.0
@lumino/example-menubar: 2.0.0-beta.1
@lumino/example-nested-dockpanel-amd: 2.0.0-beta.0
@lumino/algorithm: 2.0.0-beta.0
@lumino/application: 2.0.0-beta.1
@lumino/collections: 2.0.0-beta.0
@lumino/commands: 2.0.0-beta.1
@lumino/coreutils: 2.0.0-beta.0
@lumino/datagrid: 2.0.0-beta.1
@lumino/default-theme: 2.0.0-beta.1
@lumino/disposable: 2.0.0-beta.1
@lumino/domutils: 2.0.0-beta.0
@lumino/dragdrop: 2.0.0-beta.1
@lumino/keyboard: 2.0.0-beta.0
@lumino/messaging: …
```

Automated Changelog Entry for 2023.1.24-beta.1 on main

---

packages/widgets/src/commandpalette.ts
packages/widgets/src/widget.ts
review/api/widgets.api.md

This PR fixes issue [#13677](https://github.com/jupyterlab/jupyterlab/issues/13677) from jupyterlab.
Hidden items are still being re-rendered, despite the fact that they shouldn't be. 
Added a check to [```onUpdateRequest```](https://github.com/jupyterlab/lumino/blob/fa048e1680cce138af24ee1aa964f2f02b5e61f6/packages/widgets/src/commandpalette.ts#L289) to determine if an item is hidden, before re-rendering it. This will prevent hidden items from being re-rendered, thus solving the issue.

Check for hidden items before re-rendering

---

packages/widgets/src/accordionlayout.ts
packages/widgets/src/accordionpanel.ts
packages/widgets/tests/src/accordionlayout.spec.ts
packages/widgets/tests/src/accordionpanel.spec.ts
review/api/widgets.api.md

This PR fixes an accessibility issue about accordion panel:
- removes the role `tab` to the title, which is not in a `tablist` element.
- adds an ID to the widgets if necessary, to correctly link the `aria-controls` attribute of the corresponding title.

Accessibility in accordion panel

---

packages/widgets/src/menubar.ts

In https://github.com/jupyter/notebook/pull/6757, the following error was seen:
This error has probably appeared due to the conjunction of trouble with the new overflow menu feature and single item menu bar used in notebook v7.

Fix requiring position for `MenuBar` undetermined index

---

packages/widgets/src/menubar.ts
packages/widgets/tests/src/menubar.spec.ts
packages/widgets/tests/src/splitlayout.spec.ts
review/api/widgets.api.md

Right now it looks like it's possible to disable the overflow menu for a menu bar with:
```typescript
const overflowOptions = {
overflowMenuOptions: { isVisible: false, title: '' }
};
```
However `title` still needs to be provided even if `isVisible` is set to `false`.
This change makes `title` optional so this does not have to be the case anymore:
```typescript
const overflowOptions = {
overflowMenuOptions: { isVisible: false }
};
```
---
`overflowMenuOptions.overflowMenuVisible` has been renamed `overflowMenuOptions.isVisible`

Make `IOverflowMenuOptions.title` optional

---

packages/widgets/src/splitlayout.ts
packages/widgets/style/splitpanel.css

Fixes https://github.com/jupyterlab/jupyterlab/issues/14219

Disable size containment for split handle

---

examples/example-menubar/src/index.ts
packages/commands/src/index.ts

Fixes #540.
Prevents <kbd>ENTER</kbd> from being interpreted as an emoji character on Mac. Updates examples.

Prevents enter from being interpreted as emoji

---

packages/dragdrop/src/index.ts

This PR removes a `@deprecated` warning because it is actually a warning about *future* deprecation.
Fixes #559.

Remove `IDragEvent` deprecated tag

---

CHANGELOG.md

Automated Changelog Entry for 2023.3.27-0 on 1.x
```
@lumino/example-accordionpanel: 0.8.9
@lumino/example-datagrid: 0.32.9
@lumino/example-datastore: 0.21.9
@lumino/example-dockpanel: 0.21.9
@lumino/example-menubar: 0.1.4
@lumino/example-nested-dockpanel-amd: 0.4.1
@lumino/application: 1.31.4
@lumino/commands: 1.21.1
@lumino/datagrid: 0.36.9
@lumino/datastore: 0.18.4
@lumino/default-theme: 0.22.9
@lumino/disposable: 1.10.4
@lumino/dragdrop: 1.14.5
@lumino/polling: 1.11.4
@lumino/signaling: 1.11.1
@lumino/virtualdom: …
```

Automated Changelog Entry for 2023.3.27-0 on 1.x

---

packages/coreutils/src/token.ts
packages/polling/tsconfig.json
review/api/coreutils.api.md

The goal of this attribute is to improve token documentation.

Add optional `description` to `Token`

---

packages/coreutils/src/token.ts
review/api/coreutils.api.md

In #572, `Token.description` was added but not as a optional attribute. This broke backward compatibility with 2.0.0.
This fixes it by making the description optional.

Make `Token.description` optional for backward compatibility

---

.github/workflows/check-api-changes.yml
packages/datagrid/src/textrenderer.ts

Fixes #456
When dealing with astral symbols and ellipsing, datagrid generates invalid Unicode characters because of the use of `substring()`.
With the regular expression `/[\u{D800}-\u{DFFF}]/gu` we match any character falling within the range of surrogate code points. This includes both high surrogates (0xD800 to 0xDBFF) and low surrogates (0xDC00 to 0xDFFF). So any invalid Unicode character resulting from splitting a surrogate pair is removed with `replace()`.

Invalid unicode characters removed from datagrid (#456)

---

packages/dragdrop/src/index.ts

The `.lm-cursor-backdrop` div introduced in #502 was preventing dblclick events from reaching datagrid, breaking cell edit functionality.

Fix dblclick events with Drag.overrideCursor active (#547)

---

packages/virtualdom/src/index.ts
packages/widgets/src/tabbar.ts
review/api/widgets.api.md

References
[#9686 ](https://github.com/jupyterlab/jupyterlab/issues/9686) and [#1440](https://github.com/jupyterlab/jupyterlab/pull/14400)
Code changes
Easy part of #9686: added labels and tabindex="0" for sidebar elements so screen-readers can access them.
@krassowski Please review and comment to see if these are the right changes needed.

Added "tabindex=0" for sidebar accessibility

---

packages/commands/src/index.ts

The current character is "Leftwards Arrow with Hook" U+21A9 https://www.compart.com/en/unicode/U+21A9  from the "Arrows" block which often is rendered as colored emoji (CF code where U+FE0F Variation Selector-16) was added.
Replace with "Return Symbol" U+23CE from the "Miscellaneous Technical", which is more consistent as many of the other characters in this list are also from the "Miscellaneous Technical" section (Backspace, Alt, Shift..)
This should not need the Variation Selector and will have a similar look to Shift/Maj... in most fonts.

Use Actual Return character for Mac shortcuts.

---

examples/example-dockpanel/src/index.ts
packages/widgets/src/docklayout.ts
packages/widgets/tests/src/docklayout.spec.ts
review/api/widgets.api.md

The point of this new feature is to avoid the following situation:
I think it's a widely accepted convention to work in a layout of 3 panels: file tree, text editor, and preview. But if launching the preview *always* splits the editor widget, you keep winding up with 2 preview splits and you repeatedly have to drag one of the preview tabs over to the adjacent split.
To solve this I have introduced 4 new insert modes (`merge-left, merge-right, merge-top, merge-bottom`) which function like (`split-left, split-right, split-top, split-bottom`) but any existing splits will be reused. The behavior effectively changes to `tab-after` on the tab layout found to the left/right/top/bottom.
See the dockpanel example which now has a context menu for split and merge operations on the content widgets.

Splits with merge option for dock panels

---

packages/application/src/index.ts
packages/application/tests/src/index.spec.ts
review/api/application.api.md

~~This PR adds an optional `deferred` flag to the plugin options.~~
**EDIT** This PR allows to set the value 'defer' to the `autoStart` argument of a plugin.
This is related to https://github.com/jupyterlab/jupyterlab/issues/14576.
It also adds a function for activating all deferred plugins, preferably after application startup.
It does not modify the behavior of `autoStart`, which means that if `autoStart: false`, the plugin will not be activated using the dedicated function.

Add a 'defer' option to the autoStart argument

---

examples/example-datagrid/src/index.ts
packages/datagrid/src/basicmousehandler.ts
packages/datagrid/src/datagrid.ts
packages/datagrid/src/hyperlinkrenderer.ts
packages/datagrid/src/textrenderer.ts
review/api/datagrid.api.md

Implements: https://github.com/jupyterlab/lumino/issues/535 and https://github.com/bloomberg/ipydatagrid/issues/302
Automatically resizes the width of columns by double clicking on the barriers between column headers.

Resize column to fit text on double click

---

packages/widgets/src/tabbar.ts
packages/widgets/tests/src/tabbar.spec.ts
review/api/widgets.api.md

References
https://github.com/jupyterlab/jupyterlab/issues/9686
Code changes
Hard part of #9686: added functionality so elements now respond to "enters" or "spaces"on a keyboard like a link or button .
@krassowski Please review and comment

elements respond to enter or spacebar

---

packages/widgets/src/tabbar.ts
packages/widgets/tests/src/tabbar.spec.ts
review/api/widgets.api.md

This PR follows https://github.com/jupyterlab/lumino/pull/583 and https://github.com/jupyterlab/lumino/pull/590 to use the arrow keys for tab bar navigation.
After this PR:
By default the tab bar elements have `tabindex="-1"`, except for the current one (or the first one) which has  `tabindex="0"`. 
When a tab is focused, the arrow keys are used to change the focused tab (left/right for horizontal tab bars, up/down for vertical ones).
Pressing the tabulation again moves the focus to an element other than the tab bar. 
---
Closes https://github.com/jupyterlab/lumino/pull/581

[accessibility] Uses the arrow keys for tab bar navigation

---

packages/widgets/src/tabbar.ts

Issue number: 14814
https://github.com/jupyterlab/jupyterlab/issues/14814 
In order to make the the addLauncher button keyboard accessible when using screen reader, added the role of button to the div element. 
Tested using windows narrator. The add button is now keyboard accessible with screen reader and without it. In order to launch new launcher via keyboard: use Enter key or Spacebar Key.

Added role of button to addButton to make itkeyboard accessible when using screenreader

---

examples/example-datagrid/src/index.ts
packages/datagrid/src/asynccellrenderer.ts
packages/datagrid/src/datagrid.ts
packages/datagrid/src/imagerenderer.ts
packages/datagrid/src/index.ts
packages/datagrid/tests/src/imagerenderer.spec.ts
packages/datagrid/tests/src/index.spec.ts
review/api/datagrid.api.md

This is a step towards fixing https://github.com/bloomberg/ipydatagrid/issues/253
Prior to this change, the Lumino datagrid would not allow rendering cells asynchronously. This means that rendering images was not really possible (unless the cell renderer had a reference to the datagrid and requested a redraw once the asynchronous task was done).
This PR introduces the `AsyncCellRenderer` abstract class, which the datagrid uses as following (more or less pseudo-code):
```typescript
if (renderer instanceof AsyncCellRenderer) {
if (!renderer.isReady(config)) {
// Paint a placeholder, waiting for all asynchronous tasks to be performed
renderer.paintPlaceholder(gc, config);
// Perform all asynchronous tasks (without waiting) then redraw the region of the cell
renderer.load(config).then(() => { …
```

Datagrid: Introduce AsyncCellRenderer and ImageRenderer

---

packages/widgets/tests/src/tabbar.spec.ts

**References**
Related PR - https://github.com/jupyterlab/lumino/pull/615
**Code changes**
Added a test to check the add tab button has a role of button. This allows the user to tab to it using a keyboard.
**User-facing changes**
None
**Backwards-incompatible changes**
None

Added a test to check the add tab button has a role of button

---

packages/application/src/index.ts
review/api/application.api.md

This PR adds an experimental parameter when starting application to handle the keydown event at bubbling phase.
Currently the keydown events are handled at capture phase. With this PR it with possible to switch from capture to bubbling at startup.
See https://github.com/jupyterlab/jupyterlab/pull/14115#issuecomment-1727686379 for context.
cc. @fcollonval @krassowski @gabalafou

Keydown event at bubbling phase

---

.github/workflows/license-header.yml

Changes required following hub deprecation: https://github.com/actions/runner-images/issues/8362

Switch from `hub` to `gh` CLI

---

packages/dragdrop/style/index.css

Ref: https://github.com/jupyter/nbdime/pull/723
This ensures that the drag image is correctly positioned in applications which add non-absolutely positioned containers to the `<body>`.

Add default top/left for `.lm-mod-drag-image`

---

packages/dragdrop/src/index.ts
packages/dragdrop/style/index.css
packages/dragdrop/tests/src/index.spec.ts

Fixes https://github.com/jupyterlab/jupyterlab/issues/14881
- makes the `.lm-cursor-backdrop` scrollable using a pseudo-element and stlyes, but hiding the scrollbar
- propagates intercepted scroll events to relevant element with `data-lm-dragscroll` property
- adds `top`/`left` to `.lm-cursor-backdrop` as in https://github.com/jupyterlab/lumino/pull/651
Restoring scrolling in browser when dragging cells:
Once https://github.com/jupyterlab/jupyterlab/pull/15318 is in, also enables scrolling in file browser with selection
None

Propagate scroll from backdrop

---

packages/application/src/index.ts
review/api/application.api.md

This PR is a follow up of https://github.com/jupyterlab/lumino/pull/635, to remove an experimental implementation.
The keyboard event mode cannot be dynamically set up anymore, only when the application starts.

Remove dynamic keyboard event mode

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts

Necessary for [jupyterlab issue #15046](https://github.com/jupyterlab/jupyterlab/issues/15046) .
relevant discussion captured in #570.
Simply appends an `isKeybinding` argument to `args` in `_executeKeyBinding`.

adds isKeybinding arg to _executeKeyBinding

---

examples/example-accordionpanel/package.json
examples/example-datagrid/package.json
examples/example-dockpanel/package.json
examples/example-menubar/package.json
packages/application/package.json
packages/commands/package.json
packages/datagrid/package.json
packages/default-theme/package.json
packages/dragdrop/package.json
packages/widgets/package.json
yarn.lock

This follows an earlier [v2023.9.25-alpha.0](https://github.com/jupyterlab/lumino/releases/tag/v2023.9.25-alpha.0).

Update versions for a new release

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts

This removes the processing of keydown event by the commands registry if it is prevented (aka already treated).

Skip processing prevented default key event

---

packages/commands/src/index.ts
packages/commands/tests/src/index.spec.ts
review/api/commands.api.md

Closes https://github.com/jupyterlab/lumino/issues/688
- Adds `preventDefault` option to `IKeyBinding` and `IKeyBindingOptions` to enable downstreams to opt out of preventing default on the processed keyboard events
- Adds `CommandRegistry.holdKeyBindingExecution(event: KeyboardEvent, permission: Promise<boolean>): void;` method which enables downstream to hold the execution of a keybinding until the permission to execute resolves to `true`, or to prevent it if it resolves with `false`

Optional prevent default and asynchronous hold for keybinding execution

---

packages/widgets/src/menu.ts
packages/widgets/tests/src/menu.spec.ts
review/api/widgets.api.md

Implements enhancement #699.
This exposes the `Widget.attach` optional arguments `host` and `ref` in `Menu.IOptions` to provide greater control over exactly where in the DOM the menu `div` is attached.
I have kept the names and descriptions of the options the same as in `Widget.attach`.

Support host and ref options in Menu.open

---

packages/widgets/src/commandpalette.ts
packages/widgets/tests/src/commandpalette.spec.ts

Fixes https://github.com/jupyterlab/jupyterlab/issues/9659.
Allows search results in the command palette to be interleaved across groups.
Before the change, low-scoring search results are still grouped together, leaving higher-scoring search results in other groups lower:
After the change, search results are strictly sorted in descending score order. Headers for the same group may occur more than once. If two successive search results have the same header, then we don't display a new header.

Interleaves search results across categories

---

.github/workflows/tests.yml
examples/example-accordionpanel/package.json
examples/example-datagrid/package.json
examples/example-dockpanel-amd/package.json
examples/example-dockpanel-iife/package.json
examples/example-dockpanel/package.json
examples/example-menubar/package.json
examples/example-nested-dockpanel-amd/package.json
packages/algorithm/package.json
packages/application/package.json
packages/collections/package.json
packages/commands/package.json
packages/coreutils/package.json
packages/datagrid/package.json
packages/default-theme/package.json
packages/disposable/package.json
packages/domutils/package.json
packages/dragdrop/package.json
packages/keyboard/package.json
packages/messaging/package.json
packages/polling/package.json
packages/properties/package.json
packages/signaling/package.json
packages/virtualdom/package.json
packages/widgets/package.json
yarn.lock

PRs included in the coming release:
* Accept individual modifier keys as valid keybindings by @g547315 in https://github.com/jupyterlab/lumino/pull/637
* Datagrid: Add a public API to get the current viewport by @martinRenou in https://github.com/jupyterlab/lumino/pull/695
* Support host and ref options in Menu.open by @ianthomas23 in https://github.com/jupyterlab/lumino/pull/700
* Extract plugin handling in a `PluginRegistry` class independent of the `Application` by @fcollonval in https://github.com/jupyterlab/lumino/pull/703
* Interleaves search results across categories by @JasonWeill in https://github.com/jupyterlab/lumino/pull/706
---
* Align typedoc config with JupyterLab by @fcollonval in https://github.com/jupyterlab/lumino/pull/696
* Switch from karma to web-test-runner by …

Bump versions and fix yarn installation in CI

---

packages/widgets/style/widget.css

This removes the `overflow: hidden` CSS rule on widget.
The rationale behind this change is that 
* this is highly unexpected in the web
* it is very hard to work around as widget are nested within widgets that a app plugin does not control
It breaks the ability to have sub items overflow for example one having custom list picker or context menus in cell outputs.

Remove the overflow rule on widgets

---

packages/widgets/src/menu.ts
packages/widgets/tests/src/menu.spec.ts
review/api/widgets.api.md

Closes #709 
Adds an "align" option to Menu.IOpenOptions that can be set to "left" or "right" and adjusts the menu position so the top left or right corner is matched to the given x and y coordinates based on the given align value. It defaults to left or right depending on the document `dir` attribute to account for the given language direction.

Add `horizontalAlignment` to `Menu.open()` options

---

CONTRIBUTING.md
packages/datagrid/src/datagrid.ts
packages/widgets/src/accordionpanel.ts
packages/widgets/src/boxpanel.ts
packages/widgets/src/dockpanel.ts
packages/widgets/src/menubar.ts
packages/widgets/src/splitlayout.ts

Dear maintainers
this pull request adds the links to the examples from the related API pages.
The values of some options are also made explicit in the documentation: the additions are not exhaustive, I've added those I've used ... :grin:
While working on the documentation I couldn't find instructions about how to specifically contribute  to the documentation: I've took the liberty to add a small paragraph about that in `CONTRIBUTING.md`.
Perhaps I just missed the related documentation...
This pull request closes #740.
Thanks for considering it.

Add links to the examples and documentation contribution instructions

---

buildutils/src/rollup.tests.config.js
packages/widgets/src/commandpalette.ts
packages/widgets/src/widget.ts
packages/widgets/tests/src/commandpalette.spec.ts
packages/widgets/tests/src/tabbar.spec.ts
packages/widgets/tests/src/widget.spec.ts
review/api/widgets.api.md

Fixes #744
- Add new method `Widget.isWithinHiddenWidget` to test if a widget is hidden or within an hidden parent
> I'm not happy with the name `isWithinHiddenWidget` nor with `isAnyHidden`. Happy to change it to something else; I thought about `isAnyParentHidden`
I would recommend merging #745 prior to this to ensure tests are passing on CI.
---
This PR has two side effects:
- commenting a left over skipped test from #745 - the skipped test are marked as failing when run in debug mode but not otherwise it seems. I have no ideas why this is happening.
- I turn on the generation of source maps for tests; this makes debugging much more efficient.

Don't refresh if palette is within a hidden branch

---

packages/widgets/src/menu.ts

Here is a proposal on how to fix the issue: https://github.com/jupyterlab/jupyterlab/issues/17501
This was found when working on another accessibility issue. PR: https://github.com/jupyterlab/jupyterlab/pull/17472
References used:
https://www.w3.org/TR/wai-aria/states_and_properties#introstates
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/menuitemcheckbox_role
@krassowski ^

fix: improve accessibility for menu items with toggle state

---

.github/workflows/codeql-analysis.yml
.github/workflows/license-header.yml

Ubuntu 20.04 is no longer supported on GH Actions, see https://github.com/actions/runner-images/issues/11101
These two workflows are currently failing to run on PRs:
The codeql template recommends using `ubuntu-latest` anyways.

Run workflows that were pinned to no-longer supported `ubuntu-20.04` on `ubuntu-latest`

---

examples/example-accordionpanel/package.json
examples/example-datagrid/package.json
examples/example-dockpanel/package.json
examples/example-menubar/package.json
packages/application/package.json
packages/datagrid/package.json
packages/default-theme/package.json
packages/widgets/package.json
yarn.lock

```
Changes:
- @lumino/example-accordionpanel: 2.1.9 => 2.1.10 (private)
- @lumino/example-datagrid: 2.1.9 => 2.1.10 (private)
- @lumino/example-dockpanel: 2.1.9 => 2.1.10 (private)
- @lumino/example-menubar: 2.1.9 => 2.1.10 (private)
- @lumino/application: 2.4.3 => 2.4.4
- @lumino/datagrid: 2.5.1 => 2.5.2
- @lumino/default-theme: 2.1.9 => 2.1.10
- @lumino/widgets: 2.7.0 => 2.7.1
```

Bump versions for v2025.4.30
